import types
from .devices import Encoder as Encoder, HostEvents as HostEvents, Joystick as Joystick, Keypad as Keypad, Touch as Touch
from _typeshed import Incomplete

DEFAULT_REFRESH_MS: int
SERVICE_TICK_MS: int

class _TimerSubscription:
    def __init__(self, app, entry) -> None: ...
    def cancel(self) -> None: ...

class _RefreshClaim:
    def __init__(self, app) -> None: ...
    def release(self) -> None: ...

class _RefreshPaused:
    def __init__(self, app) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...

class App:
    @classmethod
    def current(cls): ...
    devices: Incomplete
    host_dev: Incomplete
    touch_dev: Incomplete
    keypad_dev: Incomplete
    encoder_dev: Incomplete
    joystick_dev: Incomplete
    def __init__(self, board_config=None, *, displays=None, host_read=None, touch_read=None, touch_rotation_table=None, refresh_period=None, timer_async=None) -> None: ...
    @property
    def timer_async(self): ...
    @property
    def displays(self): ...
    @property
    def primary(self): ...
    @property
    def quit_requested(self): ...
    @property
    def before_quit(self): ...
    @before_quit.setter
    def before_quit(self, value) -> None: ...
    def add_display(self, drv): ...
    def remove_display(self, drv) -> None: ...
    def add_touch(self, read, *, display=None, rotation_table=None): ...
    def add_keypad(self, read): ...
    def add_encoder(self, read, *, button_read=None, button: int = 2): ...
    def add_joystick(self, joystick_driver, *, emulate_digital=None, digital_threshold: float = 0.5): ...
    def register(self, dev) -> None: ...
    def unregister(self, dev) -> None: ...
    def on(self, event_type_or_list, callback=None): ...
    def off(self, event_type_or_list, callback) -> None: ...
    def every(self, ms, callback=None): ...
    def stop_timer(self) -> None: ...
    def pause_refresh(self): ...
    def resume_refresh(self) -> None: ...
    def refresh_paused(self): ...
    def poll(self): ...
    def arm_async_refresh(self) -> None: ...
    def run(self, tick_ms=...) -> None: ...
    def run_async(self, coro_or_fn): ...
    def request_quit(self, code=None) -> None: ...
