from _typeshed import Incomplete

HOST: Incomplete
POINTER: Incomplete
ENCODER: Incomplete
KEYPAD: Incomplete
JOYSTICK: Incomplete
SWAP_XY: Incomplete
REVERSE_X: Incomplete
REVERSE_Y: Incomplete

class Device:
    type: int
    app: Incomplete
    user_data: Incomplete
    def __init__(self) -> None: ...
    def subscribe(self, callback, event_types=None) -> None: ...
    def unsubscribe(self, callback, event_types=None) -> None: ...

class Touch(Device):
    type = POINTER
    points: Incomplete
    def __init__(self, read, display=None, rotation_table=None) -> None: ...
    @property
    def rotation(self): ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    def inject_clear(self) -> None: ...
    def inject_point(self, xy) -> None: ...
    def inject_tap(self, x, y, hold_frames: int = 1) -> None: ...
    def poll(self, *args): ...

class Keypad(Device):
    type = KEYPAD
    def __init__(self, read) -> None: ...
    def poll(self, *args): ...

class Encoder(Device):
    type = ENCODER
    def __init__(self, read, *, button_read=None, button: int = 2) -> None: ...
    def poll(self, *args): ...

class Joystick(Device):
    type = JOYSTICK
    driver: Incomplete
    emulate_digital: Incomplete
    digital_threshold: Incomplete
    def __init__(self, joystick_driver, *, emulate_digital=None, digital_threshold: float = 0.5) -> None: ...
    def poll(self, *args): ...

class HostEvents(Device):
    type = HOST
    scale: Incomplete
    def __init__(self, host_read, display=None, event_filter=None) -> None: ...
    def poll(self, *args): ...

class TouchGrid:
    x: Incomplete
    y: Incomplete
    w: Incomplete
    h: Incomplete
    cols: Incomplete
    rows: Incomplete
    key_width: Incomplete
    key_height: Incomplete
    def __init__(self, app, x, y, w, h, cols: int = 3, rows: int = 3, keys=None, translate=None, on_press=None, on_release=None) -> None: ...
    def read(self): ...
    def read_held(self): ...

class JoyMap:
    def __init__(self, app, joymap) -> None: ...
    def read(self): ...
