import ctypes
from .._core import _TimerCore
from _typeshed import Incomplete

libc: Incomplete
librt: Incomplete
librt = libc

class _timespec(ctypes.Structure): ...
class _itimerspec(ctypes.Structure): ...
class _sigval(ctypes.Union): ...
class _sigevent(ctypes.Structure): ...
librt = libc

class Timer(_TimerCore): ...
