kind = "fbdisplay_rgbframebuffer"
slug = "qualia_tl040hds20"
title = "Qualia S3 RGB-666 with TL040HDS20 4.0\" 720x720 Square Display"
title_cp = "Qualia S3 RGB-666 with TL040HDS20 4.0\" 720x720 Square Display"
out = "fbdisplay"
circuitpython = true
port = "esp32"
mp_pin_wrap = false

mp_imports = ["from pca9554 import PCA9554"]
mp_preamble = """
def send_init_sequence(init_sequence, mosi, sck, cs):
    cs(0)
    for byte in init_sequence:
        for _ in range(8):
            mosi(byte & 0x80)
            sck(1)
            byte <<= 1
            sck(0)
    cs(1)

"""
mp_preamble_after = """
init_sequence = bytes()

i2c = I2C(0, sda=Pin(8), scl=Pin(18), freq=100000)
print(f"i2c.scan() = {i2c.scan()}")
iox = PCA9554(i2c, address=0x38)
btn_down = iox.Pin(6, Pin.IN)
btn_up = iox.Pin(5, Pin.IN)
reset = iox.Pin(2, Pin.OUT, value=1)
backlight = iox.Pin(4, Pin.OUT, value=1)

send_init_sequence(
    init_sequence,
    mosi=iox.Pin(7, Pin.OUT),
    sck=iox.Pin(0, Pin.OUT, value=0),
    cs=iox.Pin(1, Pin.OUT, value=1),
)
"""
mp_post_fb = '''
mv = memoryview(fb)
mv[::] = b"\x34\x12" * (fb.width * fb.height)
fb.refresh()

'''

cp_imports = ["import busio"]
cp_tft_pins_expr = "dict(board.TFT_PINS)"
cp_framebuffer_display = true
cp_preamble = """
init_sequence_tl040hds20 = bytes()

board.I2C().deinit()
i2c = busio.I2C(board.SCL, board.SDA)
tft_io_expander = dict(board.TFT_IO_EXPANDER)
dotclockframebuffer.ioexpander_send_init_sequence(i2c, init_sequence_tl040hds20, **tft_io_expander)
"""

[tft_pins.mp]
de = 17
vsync = 3
hsync = 46
dclk = 9
red = [1, 2, 42, 41, 40]
green = [21, 47, 48, 45, 38, 39]
blue = [10, 11, 12, 13, 14]

[tft_timings]
frequency = 16_000_000
width = 720
height = 720
hsync_pulse_width = 2
hsync_front_porch = 46
hsync_back_porch = 44
vsync_pulse_width = 2
vsync_front_porch = 16
vsync_back_porch = 18
hsync_idle_low = false
vsync_idle_low = false
de_idle_high = false
pclk_active_high = false
pclk_idle_high = false

[touch]
module = "ft6x36"
class = "FT6x36"
read_wrapper = true
rotation_table = [0, 0, 0, 0]

[touch.mp.i2c]
id = 0
sda = 8
scl = 18
freq = 100000
reuse_i2c = true

[touch.chip]
address = "0x48"

[touch.cp]
driver = "focaltouch"

[package]
touch_driver = "ft6x36"
include_rgbframebuffer = true

[[package.urls_mp]]
name = "pca9554.py"
url = "github:PyDevices/pydisplay/drivers/io_expander/pca9554.py"
