kind = "pixeldisplay"
slug = "dotstar_12x6"
title = "DotStar 12x6 grid"
strip = "dotstar"
out = "pixeldisplay"
circuitpython = true

[grid]
width = 12
height = 6
alternating = false

[cp.dotstar]
clock = "board.D13"
data = "board.D11"
brightness = 0.3

[mp.dotstar]
clock = 13
data = 11
bpp = 3
