from _typeshed import Incomplete

__all__ = ['DisplayDriver', 'alloc_buffer', 'byteswap', 'capabilities', 'color332', 'color565', 'color565_swapped', 'color_rgb', 'env_bool', 'env_float', 'env_get', 'env_int', 'env_set']

byteswap: Incomplete

def env_set(name, value) -> None: ...
def env_bool(name, default: bool = False): ...
def env_float(name, default: float = 0.0): ...
def env_get(name, default=None): ...
def env_int(name, default: int = 0): ...
def capabilities(): ...
def alloc_buffer(size): ...
def color565(r, g=None, b=None): ...
def color565_swapped(r, g: int = 0, b: int = 0): ...
def color332(r, g, b): ...
def color_rgb(color): ...

class DisplayDriver:
    needs_refresh: bool
    share_framebuffer: bool
    def framebuffers(self) -> None: ...
    byteswap: Incomplete
    touch_scale: float
    def __init__(self, *, quiet: bool = False) -> None: ...
    def __del__(self) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rotation(self) -> int: ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    @property
    def touch_device(self) -> object: ...
    @touch_device.setter
    def touch_device(self, value) -> None: ...
    def fill(self, color): ...
    def scroll(self, dx, dy) -> None: ...
    def disable_auto_byteswap(self, value: bool) -> bool: ...
    @property
    def requires_byteswap(self) -> bool: ...
    def blit_transparent(self, buf: memoryview, x: int, y: int, w: int, h: int, key: int): ...
    @property
    def vscroll(self) -> int: ...
    @vscroll.setter
    def vscroll(self, y) -> None: ...
    def set_vscroll(self, tfa: int = 0, bfa: int = 0) -> None: ...
    @property
    def tfa(self) -> int: ...
    @property
    def vsa(self) -> int: ...
    @property
    def bfa(self) -> int: ...
    def translate_point(self, point) -> tuple: ...
    def scroll_by(self, value) -> None: ...
    def scroll_to(self, value) -> None: ...
    @property
    def tfa_area(self): ...
    @property
    def vsa_area(self): ...
    @property
    def bfa_area(self): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa: int | None = None) -> int: ...
    @property
    def power(self) -> bool: ...
    @power.setter
    def power(self, value: bool) -> None: ...
    @property
    def brightness(self) -> float: ...
    @brightness.setter
    def brightness(self, value: float) -> None: ...
    def invert_colors(self, value: bool) -> None: ...
    def reset(self) -> None: ...
    def hard_reset(self) -> None: ...
    def soft_reset(self) -> None: ...
    def sleep_mode(self, value: bool) -> None: ...
    def deinit(self) -> None: ...
    def quit(self, code: int = 0, force: bool = False) -> None: ...
    def force_quit(self, code: int = 0) -> None: ...
    def show(self, *args, **kwargs) -> None: ...
