from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver

class BusDisplay(DisplayDriver):
    display_bus: Incomplete
    color_depth: Incomplete
    bgr: Incomplete
    send: Incomplete
    send_color: Incomplete
    rotation_table: Incomplete
    def __init__(self, display_bus, init_sequence=None, *, width: int = 0, height: int = 0, colstart: int = 0, rowstart: int = 0, rotation: int = 0, mirrored: bool = False, color_depth: int = 16, bgr: bool = False, invert: bool = False, reverse_bytes_in_word: bool = False, brightness: float = 1.0, backlight_pin=None, backlight_on_high: bool = True, reset_pin=None, reset_high: bool = True, power_pin=None, power_on_high: bool = True, set_column_command=..., set_row_command=..., write_ram_command=..., brightness_command=None, data_as_commands: bool = False, single_byte_bounds: bool = False, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buf: memoryview, x: int, y: int, w: int, h: int): ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int): ...
    def pixel(self, x: int, y: int, c: int): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...
    @property
    def colstart(self): ...
    @property
    def rowstart(self): ...
    @property
    def power(self) -> bool: ...
    @power.setter
    def power(self, value: bool) -> None: ...
    @property
    def brightness(self) -> float: ...
    @brightness.setter
    def brightness(self, value: float) -> None: ...
    def invert_colors(self, value: bool) -> None: ...
    def reset(self) -> None: ...
    def hard_reset(self) -> None: ...
    def soft_reset(self) -> None: ...
    def sleep_mode(self, value: bool) -> None: ...
