from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver, alloc_buffer as alloc_buffer

class EPaperDisplay(DisplayDriver):
    color_depth: Incomplete
    def __init__(self, epaper, width=None, height=None, buffer=None, color_depth=None, *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def show(self, _timer=None) -> None: ...
