from displaysys import DisplayDriver as DisplayDriver

class FBDisplay(DisplayDriver):
    share_framebuffer: bool
    color_depth: int
    def __init__(self, buffer, width=None, height=None, reverse_bytes_in_word: bool = False, *, bitmap=None, display=None, quiet: bool = False) -> None: ...
    def framebuffers(self): ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def show(self, _timer=None) -> None: ...
    def flush_rect(self, x, y, w, h): ...
