from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver, color_rgb as color_rgb

class JNDevices:
    image: Incomplete
    def __init__(self, display_drv) -> None: ...
    def read(self): ...
    def update_buffer(self, pil_image) -> None: ...

class JNDisplay(DisplayDriver):
    needs_refresh: bool
    color_depth: int
    touch_scale: float
    quit_chord: Incomplete
    def __init__(self, width, height, *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...
    def render(self, render_rect=None): ...
    def show(self, _timer=None) -> None: ...
