import graphics
from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver, color_rgb as color_rgb

HORIZONTAL: Incomplete
VERTICAL: Incomplete

class PixelFramebuffer(graphics.FrameBuffer):
    rotation: Incomplete
    def __init__(self, pixels, width, height, orientation=..., alternating: bool = True, reverse_x: bool = False, reverse_y: bool = False, top: int = 0, bottom: int = 0, rotation: int = 0) -> None: ...
    @property
    def stride(self): ...
    def blit(self) -> None: ...
    def display(self) -> None: ...

class PixelDisplay(DisplayDriver):
    color_depth: int
    def __init__(self, pixel_buffer, *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def show(self, _timer=None) -> None: ...
