from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver, color_rgb as color_rgb
from displaysys._domkeys import dom_key_scrolls_page as dom_key_scrolls_page, enrich_mod as enrich_mod, key_to_keycode as key_to_keycode, mod_mask as mod_mask

def log(*args) -> None: ...

class PSDevices:
    canvas: Incomplete
    def __init__(self, id, display=None) -> None: ...
    def read(self): ...

class PSDisplay(DisplayDriver):
    needs_refresh: bool
    requires_async_timer: bool
    quit_chord: Incomplete
    color_depth: int
    touch_scale: float
    get_events: Incomplete
    def __init__(self, id, width=None, height=None, *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...
    def render(self, render_rect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
    def map_pointer(self, local_x, local_y): ...
    def map_pointer_rel(self, dx, dy): ...
