from _typeshed import Incomplete
from displaysys import DisplayDriver as DisplayDriver, color_rgb as color_rgb, fit_scale_to_desktop as fit_scale_to_desktop, notify_board_config_scale_override as notify_board_config_scale_override

def poll_event(): ...
def get_events(): ...
def retcheck(retvalue) -> None: ...

class SDLDisplay(DisplayDriver):
    needs_refresh: bool
    color_depth: Incomplete
    touch_scale: float
    quit_chord: Incomplete
    def __init__(self, width: int = 320, height: int = 240, rotation: int = 0, color_depth: int = 16, title: str = 'SDL2 Display', scale: float = 1.0, window_flags=..., render_flags=..., x=..., y=..., *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buffer: memoryview, x: int, y: int, w: int, h: int): ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int): ...
    def pixel(self, x: int, y: int, c: int): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...
    @property
    def frame_recording(self) -> bool: ...
    def open_frame_recorder(self, path, *, fps: int = 12, width=None, height=None): ...
    def close_frame_recorder(self) -> int: ...
    def render(self, renderRect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
    def capture_rgb(self) -> tuple[bytes, int, int]: ...
    def quit(self, code: int = 0, force: bool = False) -> None: ...
    def force_quit(self, code: int = 0) -> None: ...
