from displaysys import DisplayDriver

__all__ = ["WinDisplay", "get_events", "poll_event"]

def poll_event(): ...
def get_events(): ...

class WinDisplay(DisplayDriver):
    needs_refresh: bool
    color_depth: int
    touch_scale: float
    quit_chord: object
    runtime: object
    def __init__(
        self,
        width: int = 320,
        height: int = 240,
        rotation: int = 0,
        color_depth: int = 16,
        title: str = "Win32 Display",
        scale: float = 1.0,
        x=None,
        y=None,
        *,
        quiet: bool = False,
    ) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buffer, x: int, y: int, w: int, h: int): ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int): ...
    def pixel(self, x: int, y: int, c: int): ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...
    def render(self, renderRect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
