from _typeshed import Incomplete
from displaysys import DisplayDriver

__all__ = ['poll_event', 'get_events', 'WinDisplay']

def poll_event(): ...
def get_events(): ...

class WinDisplay(DisplayDriver):
    needs_refresh: bool
    requires_async_timer: bool
    quit_chord: Incomplete
    color_depth: Incomplete
    touch_scale: Incomplete
    runtime: Incomplete
    get_events: Incomplete
    def __init__(self, width: int = 320, height: int = 240, rotation: int = 0, color_depth: int = 16, title: str = 'Win32 Display', scale: float = 1.0, x=None, y=None, *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buffer, x, y, w, h): ...
    def fill_rect(self, x, y, w, h, c): ...
    def pixel(self, x, y, c): ...
    def vscrdef(self, tfa, vsa, bfa) -> None: ...
    def vscsad(self, vssa=None): ...
    def render(self, renderRect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
