# Upstream Peter Hinch GUI filesystem mapping for PyScript.

[files]
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/core/__init__.py" = "/utils/gui/core/__init__.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/core/colors.py" = "/utils/gui/core/colors.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/core/fplot.py" = "/utils/gui/core/fplot.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/core/nanogui.py" = "/utils/gui/core/nanogui.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/core/writer.py" = "/utils/gui/core/writer.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/__init__.py" = "/utils/gui/demos/__init__.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/aclock.py" = "/utils/gui/demos/aclock.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/aclock_large.py" = "/utils/gui/demos/aclock_large.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/aclock_ttgo.py" = "/utils/gui/demos/aclock_ttgo.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/alevel.py" = "/utils/gui/demos/alevel.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/asnano.py" = "/utils/gui/demos/asnano.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/asnano_sync.py" = "/utils/gui/demos/asnano_sync.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/clock_batt.py" = "/utils/gui/demos/clock_batt.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/clocktest.py" = "/utils/gui/demos/clocktest.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/color15.py" = "/utils/gui/demos/color15.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/color96.py" = "/utils/gui/demos/color96.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/fpt.py" = "/utils/gui/demos/fpt.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/mono_test.py" = "/utils/gui/demos/mono_test.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/round.py" = "/utils/gui/demos/round.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/scale.py" = "/utils/gui/demos/scale.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/sharptest.py" = "/utils/gui/demos/sharptest.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/demos/tbox.py" = "/utils/gui/demos/tbox.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/arial10.py" = "/utils/gui/fonts/arial10.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/arial35.py" = "/utils/gui/fonts/arial35.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/arial_50.py" = "/utils/gui/fonts/arial_50.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/courier20.py" = "/utils/gui/fonts/courier20.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/font10.py" = "/utils/gui/fonts/font10.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/font6.py" = "/utils/gui/fonts/font6.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/fonts/freesans20.py" = "/utils/gui/fonts/freesans20.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/__init__.py" = "/utils/gui/widgets/__init__.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/dial.py" = "/utils/gui/widgets/dial.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/label.py" = "/utils/gui/widgets/label.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/led.py" = "/utils/gui/widgets/led.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/meter.py" = "/utils/gui/widgets/meter.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/scale.py" = "/utils/gui/widgets/scale.py"
"https://raw.githubusercontent.com/peterhinch/micropython-nano-gui/master/gui/widgets/textbox.py" = "/utils/gui/widgets/textbox.py"
