from _typeshed import Incomplete

class Area:
    __hash__: Incomplete
    x: Incomplete
    y: Incomplete
    w: Incomplete
    h: Incomplete
    def __init__(self, x, y=None, w=None, h=None) -> None: ...
    def contains(self, x, y=None): ...
    def contains_area(self, other): ...
    def intersects(self, other): ...
    def touches_or_intersects(self, other): ...
    def shift(self, dx: int = 0, dy: int = 0): ...
    def clip(self, other): ...
    def offset(self, d1, d2=None, d3=None, d4=None): ...
    def inset(self, d1, d2=None, d3=None, d4=None): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __add__(self, other): ...
    def __iter__(self): ...
