from ._area import Area as Area

def clip_blit_bounds(canvas, source, x, y): ...
def canvas_accepts_blit_rect(canvas): ...
def canvas_accepts_blit_transparent(canvas): ...
def blit_rect_to_buffer(canvas, buf, x, y, w, h, *, bpp=...) -> None: ...
def blit_rect_dispatch(canvas, buf, x, y, w, h): ...
def try_fast_framebuffer_blit(canvas, source, x, y, key: int = -1, palette=None): ...
