import types
from _typeshed import Incomplete

BMP565_BPP: int
BMP565_BYTES_PER_PIXEL: int

def read_bmp565_header(f): ...
def load_bmp565_buffer(f, width, height, data_offset): ...
def write_bmp565_header(f, width, height, data_size) -> None: ...
def write_bmp565_rows(f, buffer, width, height) -> None: ...
def write_bmp565_file(f, buffer, width, height) -> None: ...

class BMP565:
    width: Incomplete
    height: Incomplete
    bpp: Incomplete
    BPP: Incomplete
    def __init__(self, filename=None, source=None, streamed: bool = False, mirrored: bool = False, width=None, height=None) -> None: ...
    def __call__(self, x, y, w, h): ...
    @property
    def buffer(self): ...
    def save(self, filename=None): ...
    def __getitem__(self, key): ...
    def deinit(self) -> None: ...
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def __del__(self) -> None: ...
