import types
from ._area import Area as Area
from ._blit_hooks import blit_rect_dispatch as blit_rect_dispatch

def intersect_rect(x, y, w, h, clip): ...
def crop_rgb565_buffer(buf, src_w, src_x, src_y, crop_w, crop_h): ...

class ClippedCanvas:
    def __init__(self, canvas, clip) -> None: ...
    def __getattr__(self, name): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    def pixel(self, x, y, c=None): ...
    def fill(self, c): ...
    def fill_rect(self, x, y, w, h, c): ...
    def hline(self, x, y, w, c): ...
    def vline(self, x, y, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def blit_transparent(self, buf, x, y, w, h, key): ...

class ClipContext:
    def __init__(self, draw, area) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: types.TracebackType | None) -> None: ...
