from ._area import Area as Area
from ._clip import ClipContext as ClipContext, ClippedCanvas as ClippedCanvas
from _typeshed import Incomplete

class Draw:
    canvas: Incomplete
    def __init__(self, canvas) -> None: ...
    def clip(self, x, y=None, w=None, h=None): ...
    def arc(self, x, y, r, a0, a1, c): ...
    def blit(self, source, x, y, key: int = -1, palette=None): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def blit_transparent(self, buf, x, y, w, h, key=None): ...
    def circle(self, x, y, r, c, f: bool = False): ...
    def ellipse(self, x, y, r1, r2, c, f: bool = False, m: int = 15, w=None, h=None): ...
    def fill(self, c): ...
    def fill_rect(self, x, y, w, h, c): ...
    def gradient_rect(self, x, y, w, h, c1, c2=None, vertical: bool = True): ...
    def hline(self, x, y, w, c): ...
    def line(self, x1, y1, x2, y2, c): ...
    def pixel(self, x, y, c): ...
    def poly(self, x, y, coords, c, f: bool = False): ...
    def polygon(self, points, x, y, c, angle: int = 0, center_x: int = 0, center_y: int = 0): ...
    def rect(self, x, y, w, h, c, f: bool = False): ...
    def round_rect(self, x, y, w, h, r, c, f: bool = False): ...
    def triangle(self, x1, y1, x2, y2, x3, y3, c, f: bool = False): ...
    def vline(self, x, y, h, c): ...
    def text(self, *args, **kwargs): ...
    def text8(self, *args, **kwargs): ...
    def text14(self, *args, **kwargs): ...
    def text16(self, *args, **kwargs): ...
