import types
from ._area import Area as Area
from _typeshed import Incomplete

sep: Incomplete

def text(*args, height: int = 8, **kwargs): ...
def text8(canvas, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...
def text14(canvas, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...
def text16(canvas, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...

class Font:
    font_data: Incomplete
    font_name: str
    def __init__(self, font_data=None, height=None, cached: bool = True) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    def deinit(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def draw_char(self, char, x, y, canvas, color, scale: int = 1, inverted: bool = False): ...
    def text(self, canvas, string, x, y, color, scale: int = 1, inverted: bool = False): ...
    def text_width(self, text, scale: int = 1): ...
    def export(self, filename) -> None: ...
