from ._area import Area as Area
from ._blit_hooks import clip_blit_bounds as clip_blit_bounds
from framebuf import FrameBuffer as _FrameBuffer, GS2_HMSB as GS2_HMSB, GS4_HMSB as GS4_HMSB, GS8 as GS8, MONO_HLSB as MONO_HLSB, MONO_HMSB as MONO_HMSB, MONO_VLSB as MONO_VLSB, RGB565 as RGB565

RGB888: int

class _RGB888Format:
    depth: int
    @staticmethod
    def set_pixel(framebuf, x, y, color) -> None: ...
    @staticmethod
    def get_pixel(framebuf, x, y): ...
    @staticmethod
    def fill(framebuf, color) -> None: ...
    @staticmethod
    def fill_rect(framebuf, x, y, width, height, color) -> None: ...

class FrameBuffer(_FrameBuffer):
    def __init__(self, buffer, width, height, format, *args, **kwargs) -> None: ...
    @property
    def color_depth(self): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def buffer(self): ...
    @property
    def format(self): ...
    def fill_rect(self, x, y, w, h, c): ...
    def pixel(self, x, y, c=None): ...
    def fill(self, c): ...
    def ellipse(self, x, y, rx, ry, c, f: bool = False, m: int = 15): ...
    def hline(self, x, y, w, c): ...
    def line(self, x1, y1, x2, y2, c): ...
    def poly(self, x, y, coords, c, f: bool = False): ...
    def rect(self, x, y, w, h, c, f: bool = False): ...
    def vline(self, x, y, h, c): ...
    def text(self, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None, height: int = 8): ...
    def blit(self, source, x, y, key: int = -1, palette=None): ...
    def arc(self, x, y, r, a0, a1, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def blit_transparent(self, buf, x, y, w, h, key): ...
    def circle(self, x0, y0, r, c, f: bool = False): ...
    def gradient_rect(self, x, y, w, h, c1, c2=None, vertical: bool = True): ...
    def polygon(self, points, x, y, color, angle: int = 0, center_x: int = 0, center_y: int = 0): ...
    def round_rect(self, x0, y0, w, h, r, c, f: bool = False): ...
    def triangle(self, x0, y0, x1, y1, x2, y2, c, f: bool = False): ...
    def text8(self, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...
    def text14(self, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...
    def text16(self, s, x, y, c: int = 1, scale: int = 1, inverted: bool = False, font_data=None): ...
    def scroll(self, xstep, ystep): ...
    def save(self, filename=None): ...
    def export(self, filename): ...
    @staticmethod
    def from_file(filename): ...
    @staticmethod
    def from_bitmap(buffer, width, height, format): ...
    @staticmethod
    def from_module(mod): ...
