from ._area import Area as Area
from ._blit_hooks import blit_rect_dispatch as blit_rect_dispatch, canvas_accepts_blit_transparent as canvas_accepts_blit_transparent, try_fast_framebuffer_blit as try_fast_framebuffer_blit

def arc(canvas, x, y, r, a0, a1, c): ...
def blit(canvas, source, x, y, key: int = -1, palette=None): ...
def blit_rect(canvas, buf, x, y, w, h): ...
def blit_transparent(canvas, buf, x, y, w, h, key): ...
def circle(canvas, x0, y0, r, c, f: bool = False): ...
def ellipse(canvas, x0, y0, r1, r2, c, f: bool = False, m: int = 15, w=None, h=None): ...
def fill(canvas, c): ...
def fill_rect(canvas, x, y, w, h, c): ...
def gradient_rect(canvas, x, y, w, h, c1, c2=None, vertical: bool = True): ...
def hline(canvas, x0, y0, w, c): ...
def line(canvas, x0, y0, x1, y1, c): ...
def pixel(canvas, x, y, c): ...
def poly(canvas, x, y, coords, c, f: bool = False): ...
def polygon(canvas, points, x, y, color, angle: int = 0, center_x: int = 0, center_y: int = 0): ...
def rect(canvas, x0, y0, w, h, c, f: bool = False): ...
def round_rect(canvas, x0, y0, w, h, r, c, f: bool = False): ...
def triangle(canvas, x0, y0, x1, y1, x2, y2, c, f: bool = False): ...
def vline(canvas, x0, y0, h, c): ...
