#!/usr/bin/env bash
# Refresh install manifests derived from src/ (packages, micropython.toml).
#
# Usage:
#   ./scripts/install_refresh_manifests.sh           # apply updates (default)
#   ./scripts/install_refresh_manifests.sh --audit   # show drift vs src/, then restore
#   ./scripts/install_refresh_manifests.sh --help

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MICROPYTHON_TOML=web/pyscript/micropython.toml
PYODIDE_TOML=web/pyscript/pyodide.toml
PYSCRIPT_JSON_CONFIGS=(
    web/pyscript/micropython.json
    web/pyscript/pyodide.json
    web/pyscript/pydevices-examples.json
    web/pyscript/peterhinch-nano.json
    web/pyscript/peterhinch-micro.json
    web/pyscript/peterhinch-touch.json
)

# PyDevices product packages (displaydev/eventsys/multimer) are micropython-lib only.
# Sister packages (pygraphics / usdl2 / palettes / pdwidgets / lvgl): frozen in
# firmware, or TestPyPI / MIP when needed — not packages/*.json from this repo.
GENERATED_LIB_PACKAGES=(
    packages/utils.json
    packages/examples.json
)

MANUAL_PACKAGES=(
    packages/micropython-micro-gui.json
    packages/micropython-nano-gui.json
    packages/micropython-touch.json
)

usage() {
    cat <<'EOF'
Usage: ./scripts/install_refresh_manifests.sh [OPTION]

Regenerate files derived from src/ for GitHub installs and PyScript.

Options:
  (none)        Run install_gen_manifests.py and update committed artifacts.
  --audit, -a   Compare generated output to the working tree, print a summary,
                then restore the original files (no changes kept).
  --help, -h    Show this message.

Generated by install_gen_manifests.py:
  packages/{utils,examples}.json
  packages/<example-subdir>.json for each src/examples/*/ (except personal)
  web/pyscript/micropython.json
  web/pyscript/pyodide.json
  web/pyscript/pydevices-examples.json
  web/pyscript/peterhinch-{nano,micro,touch}.json
  web/pyscript/packages → ../../packages (symlink)

Legacy TOML configs are generated only when explicitly requested:
  python3 scripts/install_gen_manifests.py --toml

`eventsys` is not emitted as packages/eventsys.json — install from
the micropython-lib MIP index (`displaydev` / `multimer` / `events` / `keys`
come from pydevices via that same index). Sister packages
(pygraphics / palettes / pdwidgets / lvgl / usdl2) may be frozen in MP WASM;
gallery deps skip those for MicroPython (see scripts/url_maker.py). Pyodide /
CPython install them from TestPyPI when needed (native `pygraphics` package;
MicroPython MIP still uses the pure-Python `pygraphics` package).

Not generated here (edit manually):
  packages/micropython-{micro-gui,nano-gui,touch}.json
  (bus/touch chip MIP packages: sibling pydevices/packages/)

Other scripts (see scripts/README.md):
  gallery_generator.py — browser gallery cards only
EOF
}

list_package_diff() {
    local old_path="$1" new_path="$2"
    python3 - "$old_path" "$new_path" <<'PY'
import json
import sys

def dest_paths(pkg_data):
    return {entry[0] for entry in pkg_data.get("urls", [])}

old_path, new_path = sys.argv[1], sys.argv[2]
with open(old_path) as f:
    old = json.load(f)
with open(new_path) as f:
    new = json.load(f)
old_set = dest_paths(old)
new_set = dest_paths(new)
added = sorted(new_set - old_set)
removed = sorted(old_set - new_set)
if not added and not removed:
    sys.exit(0)
name = old_path.rsplit("/", 1)[-1]
print(f"\n{name}:")
for path in added:
    print(f"  + {path}")
for path in removed:
    print(f"  - {path}")
PY
}

example_package_jsons() {
    find packages -maxdepth 1 -type f -name '*.json' ! -name 'examples.json' \
        | while read -r path; do
            stem="${path#packages/}"
            stem="${stem%.json}"
            case " ${GENERATED_LIB_PACKAGES[*]} ${MANUAL_PACKAGES[*]} " in
                *" packages/${stem}.json "*) continue ;;
            esac
            if [[ -d "src/examples/${stem}" ]]; then
                echo "$path"
            fi
        done | sort
}

audit_repo_packages() {
    local tmp
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' RETURN

    echo "Backing up generated files to $tmp"
    cp -a packages "$tmp/"
    cp "$MICROPYTHON_TOML" "$tmp/micropython.toml"
    cp "$PYODIDE_TOML" "$tmp/pyodide.toml"
    mkdir -p "$tmp/pyscript-json"
    for path in "${PYSCRIPT_JSON_CONFIGS[@]}"; do
        cp "$path" "$tmp/pyscript-json/$(basename "$path")"
    done

    echo "Running scripts/install_gen_manifests.py..."
    python3 scripts/install_gen_manifests.py

    local generated=("${GENERATED_LIB_PACKAGES[@]}")
    local example_pkgs=()
    mapfile -t example_pkgs < <(example_package_jsons)
    generated+=("${example_pkgs[@]}")
    generated+=("${PYSCRIPT_JSON_CONFIGS[@]}")

    echo
    echo "=== File-level diff ==="
    local changed=0
    for path in "${generated[@]}"; do
        case "$path" in
            packages/*)
                if ! diff -q "$tmp/packages/${path#packages/}" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
            "$MICROPYTHON_TOML")
                if ! diff -q "$tmp/micropython.toml" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
            "$PYODIDE_TOML")
                if ! diff -q "$tmp/pyodide.toml" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
            web/pyscript/micropython.json|web/pyscript/pyodide.json|web/pyscript/pydevices-examples.json|web/pyscript/peterhinch-*.json)
                if ! diff -q "$tmp/pyscript-json/$(basename "$path")" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
        esac
    done
    if [[ "$changed" -eq 0 ]]; then
        echo "No differences — generated files match src/."
    fi

    echo
    echo "=== Package entry diff (dest paths) ==="
    for path in "${generated[@]}"; do
        case "$path" in
            packages/*)
                list_package_diff \
                    "$tmp/packages/${path#packages/}" \
                    "$path" || true
                ;;
        esac
    done

    echo
    echo "Restoring original files (audit mode does not keep changes)."
    rm -rf packages
    cp -a "$tmp/packages" packages/
    cp "$tmp/micropython.toml" "$MICROPYTHON_TOML"
    cp "$tmp/pyodide.toml" "$PYODIDE_TOML"
    for path in "${PYSCRIPT_JSON_CONFIGS[@]}"; do
        cp "$tmp/pyscript-json/$(basename "$path")" "$path"
    done

    if [[ "$changed" -ne 0 ]]; then
        echo
        echo "ERROR: generated files are stale — run ./scripts/install_refresh_manifests.sh"
        exit 1
    fi
}

regenerate_repo_packages() {
    echo "Running scripts/install_gen_manifests.py..."
    python3 scripts/install_gen_manifests.py
    echo
    echo "Updated lib packages:"
    for path in "${GENERATED_LIB_PACKAGES[@]}"; do
        echo "  $path"
    done
    echo "Updated example packages:"
    example_package_jsons | while read -r path; do
        echo "  $path"
    done
    for path in "${PYSCRIPT_JSON_CONFIGS[@]}"; do
        echo "  $path"
    done
    echo "  web/pyscript/packages (symlink)"
    echo
    echo "Remember to review git diff. Manual packages were not changed:"
    for path in "${MANUAL_PACKAGES[@]}"; do
        echo "  $path"
    done
}

case "${1:-}" in
    --audit|-a)
        audit_repo_packages
        ;;
    --help|-h)
        usage
        ;;
    "" )
        regenerate_repo_packages
        ;;
    *)
        echo "Unknown option: $1" >&2
        usage >&2
        exit 1
        ;;
esac
