#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Brad Barnett
#
# SPDX-License-Identifier: MIT
"""Regenerate pdwidgets WIDGET_DEPS.md from AST of widgets/*.py.

Run from repo root::

    .venv/bin/python scripts/pdwidgets_widget_deps.py

Writes ``src/add_ons/pdwidgets/WIDGET_DEPS.md``. Pass ``--check`` to exit
non-zero if the file would change (for CI).
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
WIDGETS_DIR = ROOT / "src" / "add_ons" / "pdwidgets" / "widgets"
OUT_PATH = ROOT / "src" / "add_ons" / "pdwidgets" / "WIDGET_DEPS.md"

HEADER = """\
# pdwidgets widget dependency graph

Auto-generated by `scripts/pdwidgets_widget_deps.py` — do not edit by hand.
Regenerate from repo root:

```bash
.venv/bin/python scripts/pdwidgets_widget_deps.py
```

## Always-on core (every UI)

Ship these regardless of which widgets you use:

- `widget`, `display`, `screen`, `task`, `_constants`, `_themes`, `_util`, `_focus`

Everything under `widgets/` is optional cargo. Prefer lean imports:

```python
from pdwidgets.widgets.button import Button
```

Convenience `import pdwidgets as pd` resolves names lazily via `__getattr__`
(loads a widget module on first access). Icons under `icons/` are optional —
omit them if no `IconTheme` / `.pbm` assets are used.

## Widget → direct peer imports

| Widget module | Direct imports |
|---|---|
"""


def _peer_imports(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    peers: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.module is None:
                continue
            # from .foo import …  or from ..bar import …
            if node.level == 1:
                # relative within widgets/
                mod = node.module.split(".")[0]
                if mod and not mod.startswith("_"):
                    peers.add(mod)
            elif node.level == 2:
                # package-level (themes, widget, …) — note as core/other
                mod = node.module.split(".")[0]
                if mod:
                    peers.add(f"..{mod}")
    return sorted(peers)


def build_markdown() -> str:
    rows = []
    for path in sorted(WIDGETS_DIR.glob("*.py")):
        if path.name.startswith("_") or path.name == "__init__.py":
            continue
        peers = _peer_imports(path)
        cell = ", ".join(f"`{p}`" for p in peers) if peers else "_(none)_"
        rows.append(f"| `{path.stem}` | {cell} |")
    return HEADER + "\n".join(rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if WIDGET_DEPS.md would change",
    )
    args = parser.parse_args(argv)
    text = build_markdown()
    if args.check:
        if not OUT_PATH.is_file() or OUT_PATH.read_text(encoding="utf-8") != text:
            print("WIDGET_DEPS.md is stale; run scripts/pdwidgets_widget_deps.py", file=sys.stderr)
            return 1
        print("WIDGET_DEPS.md up to date")
        return 0
    OUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
