interpreter = "./vendor/micropython/micropython.mjs"

[files]
"./src/utils/byteswap.py" = "/utils/"
"./src/utils/frame_recorder.py" = "/utils/"
"./src/utils/keypins.py" = "/utils/"
"./src/utils/micropython.py" = "/utils/"
"./src/utils/mip.py" = "/utils/"
"./src/utils/viper_tools.py" = "/utils/"
"./src/utils/wifi.py" = "/utils/"

"./src/utils/audio.py" = "/utils/"
"./src/utils/color_setup.py" = "/utils/"
"./src/utils/console.py" = "/utils/"
"./src/utils/displaybuf.py" = "/utils/"
"./src/utils/fetch_ph_gui.py" = "/utils/"
"./src/utils/framebuf.py" = "/utils/"
"./src/utils/hardware_setup.py" = "/utils/"
"./src/utils/itertools.py" = "/utils/"
"./src/utils/lv_encoder_emu.py" = "/utils/"
"./src/utils/path.py" = "/utils/"
"./src/utils/png.py" = "/utils/"
"./src/utils/secrets.py" = "/utils/"
"./src/utils/tft_bitmap.py" = "/utils/"
"./src/utils/tft_config.py" = "/utils/"
"./src/utils/tft_text.py" = "/utils/"
"./src/utils/tft_write.py" = "/utils/"
"./src/utils/touch_setup.py" = "/utils/"
"./src/utils/tree.py" = "/utils/"
"./src/utils/uctypes.py" = "/utils/"
"./src/utils/fonts/__init__.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_16x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_16x32.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_8x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_8x8.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_bold_16x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga1_bold_16x32.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_16x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_16x32.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_8x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_8x8.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_bold_16x16.py" = "/utils/fonts/"
"./src/utils/fonts/vga2_bold_16x32.py" = "/utils/fonts/"
"./src/utils/pixel_sim/__init__.py" = "/utils/pixel_sim/"

"./src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"./src/lib/eventsys/_capabilities.py" = "/lib/eventsys/"
"./src/lib/eventsys/_device.py" = "/lib/eventsys/"
"./src/lib/eventsys/_encoder.py" = "/lib/eventsys/"
"./src/lib/eventsys/_host.py" = "/lib/eventsys/"
"./src/lib/eventsys/_joystick.py" = "/lib/eventsys/"
"./src/lib/eventsys/_keypad.py" = "/lib/eventsys/"
"./src/lib/eventsys/_runtime.py" = "/lib/eventsys/"
"./src/lib/eventsys/_touch.py" = "/lib/eventsys/"
"./src/lib/eventsys/joystick_keys.py" = "/lib/eventsys/"
"./src/lib/eventsys/touch_keypad.py" = "/lib/eventsys/"

"./src/utils/ps_loader.py" = "/"
