interpreter = "./vendor/micropython/micropython.mjs"

[files]
"./src/add_ons/README.md" = "/add_ons/"
"./src/add_ons/byteswap.py" = "/add_ons/"
"./src/add_ons/color_setup.py" = "/add_ons/"
"./src/add_ons/console.py" = "/add_ons/"
"./src/add_ons/display_driver.py" = "/add_ons/"
"./src/add_ons/displaybuf.py" = "/add_ons/"
"./src/add_ons/fetch_ph_gui.py" = "/add_ons/"
"./src/add_ons/framebuf.py" = "/add_ons/"
"./src/add_ons/hardware_setup.py" = "/add_ons/"
"./src/add_ons/itertools.py" = "/add_ons/"
"./src/add_ons/keypins.py" = "/add_ons/"
"./src/add_ons/lv_utils.py" = "/add_ons/"
"./src/add_ons/micropython.py" = "/add_ons/"
"./src/add_ons/png.py" = "/add_ons/"
"./src/add_ons/tft_bitmap.py" = "/add_ons/"
"./src/add_ons/tft_config.py" = "/add_ons/"
"./src/add_ons/tft_text.py" = "/add_ons/"
"./src/add_ons/tft_write.py" = "/add_ons/"
"./src/add_ons/touch_setup.py" = "/add_ons/"
"./src/add_ons/uctypes.py" = "/add_ons/"
"./src/add_ons/usdl2.py" = "/add_ons/"
"./src/add_ons/viper_tools.py" = "/add_ons/"
"./src/add_ons/wifi.py" = "/add_ons/"
"./src/add_ons/fonts/__init__.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/compile_upload.sh" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_16x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_16x32.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_8x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_8x8.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_bold_16x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga1_bold_16x32.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_16x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_16x32.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_8x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_8x8.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_bold_16x16.py" = "/add_ons/fonts/"
"./src/add_ons/fonts/vga2_bold_16x32.py" = "/add_ons/fonts/"
"./src/add_ons/palettes/__init__.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/_cube125.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/_cube27.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/_cube64.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/_cube8.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/_material_design.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/cube.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/material_design.py" = "/add_ons/palettes/"
"./src/add_ons/palettes/wheel.py" = "/add_ons/palettes/"
"./src/add_ons/pdwidgets/WIDGET_DEPS.md" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/__init__.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/_constants.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/_focus.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/_themes.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/_util.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/console.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/display.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/pct.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/screen.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/task.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/widget.py" = "/add_ons/pdwidgets/"
"./src/add_ons/pdwidgets/icons/LICENSE" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/README.md" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/add_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/add_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/add_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/add_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/battery_full_color_24dp.bmp" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/bluetooth_color_24dp.bmp" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_outline_blank_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_outline_blank_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_outline_blank_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/check_box_outline_blank_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/close_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/close_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/close_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/close_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/error_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/error_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/error_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/error_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/expand_more_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/expand_more_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/expand_more_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/expand_more_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/home_filled_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/home_filled_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/home_filled_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/home_filled_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/info_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/info_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/info_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/info_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_down_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_down_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_down_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_down_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_left_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_left_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_left_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_left_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_right_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_right_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_right_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_right_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_up_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_up_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_up_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/keyboard_arrow_up_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/menu_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/menu_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/menu_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/menu_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/notifications_color_24dp.bmp" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_checked_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_checked_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_checked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_checked_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_unchecked_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_unchecked_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_unchecked_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/radio_button_unchecked_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/remove_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/remove_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/remove_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/remove_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_off_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_off_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_off_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_off_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_on_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_on_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_on_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/toggle_on_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/warning_18dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/warning_24dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/warning_36dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/icons/warning_48dp.pbm" = "/add_ons/pdwidgets/icons/"
"./src/add_ons/pdwidgets/widgets/__init__.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/_layout.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/accordion.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/app_bar.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/badge.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/bottom_sheet.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/button.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/card.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/chart.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/check_box.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/chip.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/color_picker.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/column.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/date_picker.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/dialog.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/digital_clock.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/divider.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/drawer.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/dropdown.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/form.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/form_row.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/gauge.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/grid.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/icon.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/icon_button.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/image.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/keyboard.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/label.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/list_view.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/menu.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/navigator.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/number_stepper.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/page.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/password_field.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/pin_pad.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/progress_bar.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/radio_button.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/radio_group.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/row.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/scroll_bar.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/scroll_view.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/segmented_control.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/slider.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/spinner.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/switch.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/tab_view.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/text_box.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/text_input.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/toast.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/toggle.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pdwidgets/widgets/toggle_button.py" = "/add_ons/pdwidgets/widgets/"
"./src/add_ons/pixel_sim/__init__.py" = "/add_ons/pixel_sim/"
"./src/add_ons/pixel_sim/board_config.py" = "/add_ons/pixel_sim/"

"./src/lib/board_config.py" = "/lib/"
"./src/lib/path.py" = "/lib/"
"./src/lib/displaysys/__init__.py" = "/lib/displaysys/"
"./src/lib/displaysys/busdisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/epaperdisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/fbdisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/jndisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/pgdisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/pixeldisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/psdisplay.py" = "/lib/displaysys/"
"./src/lib/displaysys/sdldisplay.py" = "/lib/displaysys/"

"./src/lib/eventsys/__init__.py" = "/lib/eventsys/"
"./src/lib/eventsys/_capabilities.py" = "/lib/eventsys/"
"./src/lib/eventsys/_device.py" = "/lib/eventsys/"
"./src/lib/eventsys/_encoder.py" = "/lib/eventsys/"
"./src/lib/eventsys/_events.py" = "/lib/eventsys/"
"./src/lib/eventsys/_host.py" = "/lib/eventsys/"
"./src/lib/eventsys/_joystick.py" = "/lib/eventsys/"
"./src/lib/eventsys/_keypad.py" = "/lib/eventsys/"
"./src/lib/eventsys/_runtime.py" = "/lib/eventsys/"
"./src/lib/eventsys/_touch.py" = "/lib/eventsys/"
"./src/lib/eventsys/joystick_keys.py" = "/lib/eventsys/"
"./src/lib/eventsys/keys.py" = "/lib/eventsys/"
"./src/lib/eventsys/touch_keypad.py" = "/lib/eventsys/"

"./src/lib/graphics/__init__.py" = "/lib/graphics/"
"./src/lib/graphics/_area.py" = "/lib/graphics/"
"./src/lib/graphics/_blit_hooks.py" = "/lib/graphics/"
"./src/lib/graphics/_bmp565.py" = "/lib/graphics/"
"./src/lib/graphics/_clip.py" = "/lib/graphics/"
"./src/lib/graphics/_draw.py" = "/lib/graphics/"
"./src/lib/graphics/_files.py" = "/lib/graphics/"
"./src/lib/graphics/_font.py" = "/lib/graphics/"
"./src/lib/graphics/_font_8x14.py" = "/lib/graphics/"
"./src/lib/graphics/_font_8x16.py" = "/lib/graphics/"
"./src/lib/graphics/_font_8x8.py" = "/lib/graphics/"
"./src/lib/graphics/_framebuf_plus.py" = "/lib/graphics/"
"./src/lib/graphics/_shapes.py" = "/lib/graphics/"

"./src/lib/multimer/__init__.py" = "/lib/multimer/"
"./src/lib/multimer/_async_timer.py" = "/lib/multimer/"
"./src/lib/multimer/_asyncio_loader.py" = "/lib/multimer/"
"./src/lib/multimer/_core.py" = "/lib/multimer/"
"./src/lib/multimer/_mpasyncio.py" = "/lib/multimer/"
"./src/lib/multimer/_schedule.py" = "/lib/multimer/"
"./src/lib/multimer/_select.py" = "/lib/multimer/"
"./src/lib/multimer/_ticks.py" = "/lib/multimer/"
"./src/lib/multimer/_timer.py" = "/lib/multimer/"
"./src/lib/multimer/py.typed" = "/lib/multimer/"
"./src/lib/multimer/_backends/__init__.py" = "/lib/multimer/_backends/"
"./src/lib/multimer/_backends/librt.py" = "/lib/multimer/_backends/"
"./src/lib/multimer/_backends/polling.py" = "/lib/multimer/_backends/"
"./src/lib/multimer/_backends/sdl2.py" = "/lib/multimer/_backends/"
"./src/lib/multimer/_backends/threading.py" = "/lib/multimer/_backends/"
"./src/lib/multimer/_backends/win32.py" = "/lib/multimer/_backends/"

"./src/jupyter_notebook.ipynb" = "/"
