from ._events import events as events
from _typeshed import Incomplete

class types:
    UNDEFINED: Incomplete
    HOST: Incomplete
    POINTER: Incomplete
    ENCODER: Incomplete
    KEYPAD: Incomplete
    JOYSTICK: Incomplete

class Device:
    type: Incomplete
    responses: Incomplete
    def __init__(self, read=None, data=None, read2=None, data2=None) -> None: ...
    def poll(self, *args): ...
    def subscribe(self, callback, event_types=None) -> None: ...
    def unsubscribe(self, callback, event_types=None) -> None: ...
    @property
    def runtime(self): ...
    @runtime.setter
    def runtime(self, runtime) -> None: ...
    @property
    def user_data(self): ...
    @user_data.setter
    def user_data(self, value) -> None: ...

def register_device(type_name, responses): ...
def register_device_class(type_id, cls) -> None: ...
def device_class(type_id): ...
