from ._device import Device as Device, register_device_class as register_device_class, types as types
from ._events import events as events
from _typeshed import Incomplete

class JoystickDriver:
    def get_instance_id(self) -> None: ...
    def get_numaxes(self) -> None: ...
    def get_axis(self, axis) -> None: ...
    def get_numballs(self) -> None: ...
    def get_ball(self, ball) -> None: ...
    def get_numbuttons(self) -> None: ...
    def get_button(self, button) -> None: ...
    def get_numhats(self) -> None: ...
    def get_hat(self, hat) -> None: ...

class JoystickDevice(Device):
    type: Incomplete
    responses: Incomplete
    joystick_driver: Incomplete
    emulate_digital: Incomplete
    digital_threshold: Incomplete
    def __init__(self, *args, joystick_driver: JoystickDriver, emulate_digital=None, digital_threshold: float = 0.5, **kwargs) -> None: ...
    def emulate(self, value): ...
