import types
from ._encoder import EncoderDevice as EncoderDevice
from ._events import events as events
from ._host import HostEventsDevice as HostEventsDevice
from ._joystick import JoystickDevice as JoystickDevice
from ._keypad import KeypadDevice as KeypadDevice
from ._touch import TouchDevice as TouchDevice
from _typeshed import Incomplete

DEFAULT_REFRESH_MS: int
SERVICE_TICK_MS: int

class _RuntimeTimerSubscription:
    def __init__(self, runtime, entry) -> None: ...
    def deinit(self) -> None: ...

class _DisplayRefreshClaim:
    def __init__(self, runtime) -> None: ...
    def release(self) -> None: ...

class _DisplayRefreshPaused:
    def __init__(self, runtime) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...

class Runtime:
    events = events
    devices: Incomplete
    host_dev: Incomplete
    touch_dev: Incomplete
    keypad_dev: Incomplete
    encoder_dev: Incomplete
    joystick_dev: Incomplete
    def __init__(self, display=None, host_read=None, touch_read=None, touch_rotation_table=None, *, refresh_period=None, timer_async: bool = False) -> None: ...
    @property
    def timer_async(self): ...
    def arm_async_refresh(self) -> None: ...
    async def run(self, tick_ms=...) -> None: ...
    def run_forever(self, tick_ms=...) -> None: ...
    def run_async(self, coro_or_fn): ...
    @property
    def quit_requested(self): ...
    def request_quit(self, code=None) -> None: ...
    @property
    def before_quit(self): ...
    @before_quit.setter
    def before_quit(self, value) -> None: ...
    @property
    def display_refresh(self): ...
    def on(self, event_type, callback) -> None: ...
    def on_device(self, device_type, callback) -> None: ...
    def off(self, callback, event_type=None, device_type=None) -> None: ...
    def subscribe(self, callback, event_types=None, device_types=None) -> None: ...
    def unsubscribe(self, callback, event_types=None, device_types=None) -> None: ...
    def register(self, dev) -> None: ...
    def unregister(self, dev) -> None: ...
    def add_keypad(self, read): ...
    def add_encoder(self, read, *, button_read=None, button: int = 2): ...
    def add_joystick(self, *, joystick_driver=None, **kwargs): ...
    def poll(self): ...
    def start_timer(self, *, async_: bool = False, tick_ms: int = 10): ...
    def on_tick(self, callback, *, period, async_: bool = False): ...
    def stop_timer(self) -> None: ...
    def claim_display_refresh(self): ...
    def display_refresh_paused(self): ...
