from ._device import Device as Device, register_device_class as register_device_class, types as types
from ._events import events as events
from _typeshed import Incomplete

SWAP_XY: Incomplete
REVERSE_X: Incomplete
REVERSE_Y: Incomplete

class TouchDevice(Device):
    type: Incomplete
    responses: Incomplete
    points: Incomplete
    def __init__(self, *args, read=None, data=None, data2=None, display=None, rotation_table=None, **kwargs) -> None: ...
    @property
    def rotation(self): ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    @property
    def rotation_table(self): ...
    @rotation_table.setter
    def rotation_table(self, value) -> None: ...
    def inject_clear(self) -> None: ...
    def inject_point(self, xy) -> None: ...
    def inject_tap(self, x, y, hold_frames: int = 1) -> None: ...
