from _typeshed import Incomplete

class Keys:
    def keyname(x): ...
    def key(x): ...
    def modname(x): ...
    def mod(x): ...
    K_UNKNOWN: Incomplete
    K_BACKSPACE: Incomplete
    K_TAB: Incomplete
    K_RETURN: Incomplete
    K_ESCAPE: Incomplete
    K_SPACE: Incomplete
    K_EXCLAIM: Incomplete
    K_QUOTEDBL: Incomplete
    K_HASH: Incomplete
    K_DOLLAR: Incomplete
    K_PERCENT: Incomplete
    K_AMPERSAND: Incomplete
    K_QUOTE: Incomplete
    K_LEFTPAREN: Incomplete
    K_RIGHTPAREN: Incomplete
    K_ASTERISK: Incomplete
    K_PLUS: Incomplete
    K_COMMA: Incomplete
    K_MINUS: Incomplete
    K_PERIOD: Incomplete
    K_SLASH: Incomplete
    K_0: Incomplete
    K_1: Incomplete
    K_2: Incomplete
    K_3: Incomplete
    K_4: Incomplete
    K_5: Incomplete
    K_6: Incomplete
    K_7: Incomplete
    K_8: Incomplete
    K_9: Incomplete
    K_COLON: Incomplete
    K_SEMICOLON: Incomplete
    K_LESS: Incomplete
    K_EQUALS: Incomplete
    K_GREATER: Incomplete
    K_QUESTION: Incomplete
    K_AT: Incomplete
    K_LEFTBRACKET: Incomplete
    K_BACKSLASH: Incomplete
    K_RIGHTBRACKET: Incomplete
    K_CARET: Incomplete
    K_UNDERSCORE: Incomplete
    K_BACKQUOTE: Incomplete
    K_a: Incomplete
    K_b: Incomplete
    K_c: Incomplete
    K_d: Incomplete
    K_e: Incomplete
    K_f: Incomplete
    K_g: Incomplete
    K_h: Incomplete
    K_i: Incomplete
    K_j: Incomplete
    K_k: Incomplete
    K_l: Incomplete
    K_m: Incomplete
    K_n: Incomplete
    K_o: Incomplete
    K_p: Incomplete
    K_q: Incomplete
    K_r: Incomplete
    K_s: Incomplete
    K_t: Incomplete
    K_u: Incomplete
    K_v: Incomplete
    K_w: Incomplete
    K_x: Incomplete
    K_y: Incomplete
    K_z: Incomplete
    K_DELETE: Incomplete
    K_CAPSLOCK: Incomplete
    K_F1: Incomplete
    K_F2: Incomplete
    K_F3: Incomplete
    K_F4: Incomplete
    K_F5: Incomplete
    K_F6: Incomplete
    K_F7: Incomplete
    K_F8: Incomplete
    K_F9: Incomplete
    K_F10: Incomplete
    K_F11: Incomplete
    K_F12: Incomplete
    K_PRINTSCREEN: Incomplete
    K_SCROLLLOCK: Incomplete
    K_PAUSE: Incomplete
    K_INSERT: Incomplete
    K_HOME: Incomplete
    K_PAGEUP: Incomplete
    K_END: Incomplete
    K_PAGEDOWN: Incomplete
    K_RIGHT: Incomplete
    K_LEFT: Incomplete
    K_DOWN: Incomplete
    K_UP: Incomplete
    K_NUMLOCKCLEAR: Incomplete
    K_KP_DIVIDE: Incomplete
    K_KP_MULTIPLY: Incomplete
    K_KP_MINUS: Incomplete
    K_KP_PLUS: Incomplete
    K_KP_ENTER: Incomplete
    K_KP_1: Incomplete
    K_KP_2: Incomplete
    K_KP_3: Incomplete
    K_KP_4: Incomplete
    K_KP_5: Incomplete
    K_KP_6: Incomplete
    K_KP_7: Incomplete
    K_KP_8: Incomplete
    K_KP_9: Incomplete
    K_KP_0: Incomplete
    K_KP_PERIOD: Incomplete
    K_APPLICATION: Incomplete
    K_POWER: Incomplete
    K_KP_EQUALS: Incomplete
    K_F13: Incomplete
    K_F14: Incomplete
    K_F15: Incomplete
    K_F16: Incomplete
    K_F17: Incomplete
    K_F18: Incomplete
    K_F19: Incomplete
    K_F20: Incomplete
    K_F21: Incomplete
    K_F22: Incomplete
    K_F23: Incomplete
    K_F24: Incomplete
    K_EXECUTE: Incomplete
    K_HELP: Incomplete
    K_MENU: Incomplete
    K_SELECT: Incomplete
    K_STOP: Incomplete
    K_AGAIN: Incomplete
    K_UNDO: Incomplete
    K_CUT: Incomplete
    K_COPY: Incomplete
    K_PASTE: Incomplete
    K_FIND: Incomplete
    K_MUTE: Incomplete
    K_VOLUMEUP: Incomplete
    K_VOLUMEDOWN: Incomplete
    K_KP_COMMA: Incomplete
    K_KP_EQUALSAS400: Incomplete
    K_ALTERASE: Incomplete
    K_SYSREQ: Incomplete
    K_CANCEL: Incomplete
    K_CLEAR: Incomplete
    K_PRIOR: Incomplete
    K_RETURN2: Incomplete
    K_SEPARATOR: Incomplete
    K_OUT: Incomplete
    K_OPER: Incomplete
    K_CLEARAGAIN: Incomplete
    K_CRSEL: Incomplete
    K_EXSEL: Incomplete
    K_KP_00: Incomplete
    K_KP_000: Incomplete
    K_THOUSANDSSEPARATOR: Incomplete
    K_DECIMALSEPARATOR: Incomplete
    K_CURRENCYUNIT: Incomplete
    K_CURRENCYSUBUNIT: Incomplete
    K_KP_LEFTPAREN: Incomplete
    K_KP_RIGHTPAREN: Incomplete
    K_KP_LEFTBRACE: Incomplete
    K_KP_RIGHTBRACE: Incomplete
    K_KP_TAB: Incomplete
    K_KP_BACKSPACE: Incomplete
    K_KP_A: Incomplete
    K_KP_B: Incomplete
    K_KP_C: Incomplete
    K_KP_D: Incomplete
    K_KP_E: Incomplete
    K_KP_F: Incomplete
    K_KP_XOR: Incomplete
    K_KP_POWER: Incomplete
    K_KP_PERCENT: Incomplete
    K_KP_LESS: Incomplete
    K_KP_GREATER: Incomplete
    K_KP_AMPERSAND: Incomplete
    K_KP_DBLAMPERSAND: Incomplete
    K_KP_VERTICALBAR: Incomplete
    K_KP_DBLVERTICALBAR: Incomplete
    K_KP_COLON: Incomplete
    K_KP_HASH: Incomplete
    K_KP_SPACE: Incomplete
    K_KP_AT: Incomplete
    K_KP_EXCLAM: Incomplete
    K_KP_MEMSTORE: Incomplete
    K_KP_MEMRECALL: Incomplete
    K_KP_MEMCLEAR: Incomplete
    K_KP_MEMADD: Incomplete
    K_KP_MEMSUBTRACT: Incomplete
    K_KP_MEMMULTIPLY: Incomplete
    K_KP_MEMDIVIDE: Incomplete
    K_KP_PLUSMINUS: Incomplete
    K_KP_CLEAR: Incomplete
    K_KP_CLEARENTRY: Incomplete
    K_KP_BINARY: Incomplete
    K_KP_OCTAL: Incomplete
    K_KP_DECIMAL: Incomplete
    K_KP_HEXADECIMAL: Incomplete
    K_LCTRL: Incomplete
    K_LSHIFT: Incomplete
    K_LALT: Incomplete
    K_LGUI: Incomplete
    K_RCTRL: Incomplete
    K_RSHIFT: Incomplete
    K_RALT: Incomplete
    K_RGUI: Incomplete
    K_MODE: Incomplete
    K_AUDIONEXT: Incomplete
    K_AUDIOPREV: Incomplete
    K_AUDIOSTOP: Incomplete
    K_AUDIOPLAY: Incomplete
    K_AUDIOMUTE: Incomplete
    K_MEDIASELECT: Incomplete
    K_WWW: Incomplete
    K_MAIL: Incomplete
    K_CALCULATOR: Incomplete
    K_COMPUTER: Incomplete
    K_AC_SEARCH: Incomplete
    K_AC_HOME: Incomplete
    K_AC_BACK: Incomplete
    K_AC_FORWARD: Incomplete
    K_AC_STOP: Incomplete
    K_AC_REFRESH: Incomplete
    K_AC_BOOKMARKS: Incomplete
    K_BRIGHTNESSDOWN: Incomplete
    K_BRIGHTNESSUP: Incomplete
    K_DISPLAYSWITCH: Incomplete
    K_KBDILLUMTOGGLE: Incomplete
    K_KBDILLUMDOWN: Incomplete
    K_KBDILLUMUP: Incomplete
    K_EJECT: Incomplete
    K_SLEEP: Incomplete
    KMOD_NONE: Incomplete
    KMOD_LSHIFT: Incomplete
    KMOD_RSHIFT: Incomplete
    KMOD_LCTRL: Incomplete
    KMOD_RCTRL: Incomplete
    KMOD_LALT: Incomplete
    KMOD_RALT: Incomplete
    KMOD_LGUI: Incomplete
    KMOD_RGUI: Incomplete
    KMOD_NUM: Incomplete
    KMOD_CAPS: Incomplete
    KMOD_MODE: Incomplete
    KMOD_CTRL = KMOD_LCTRL | KMOD_RCTRL
    KMOD_SHIFT = KMOD_LSHIFT | KMOD_RSHIFT
    KMOD_ALT = KMOD_LALT | KMOD_RALT
    KMOD_GUI = KMOD_LGUI | KMOD_RGUI

def key_to_keycode(key, location: int = 0): ...
def mod_mask(ctrl, shift, alt, meta): ...
def enrich_mod(mod, pressed_keys): ...
def chord_matches(chord, keycode, mod): ...
def default_quit_chord(): ...
def key_triggers_quit(event_type, key, mod, quit_chord): ...
def dom_key_scrolls_page(keycode): ...
