#!/usr/bin/env bash
# Run pydisplay examples in Jupyter (JNDisplay / ipywidgets).
#
# Usage (from repo root):
#   ./tools/jupyter.sh calculator
#   ./tools/jupyter.sh chango
#   ./tools/jupyter.sh                          # open src/jupyter_notebook.ipynb (hub)
#   ./tools/jupyter.sh calculator --cursor      # open generated notebook in Cursor
#   ./tools/jupyter.sh calculator --no-open     # generate notebook / start server only
#
# Browser mode starts JupyterLab with notebook-dir=src/ (see docs/platforms/jupyter-run.md).
# Cursor mode skips the server and opens the notebook in the editor.

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYDISPLAY_ROOT="${PYDISPLAY_ROOT:-$(cd "$_SCRIPT_DIR/.." && pwd)}"
SRC="$PYDISPLAY_ROOT/src"
HUB_NOTEBOOK="$SRC/jupyter_notebook.ipynb"
VENV="${JUPYTER_VENV:-$PYDISPLAY_ROOT/.venv}"
PORT=8888
DEMO=""
OPEN=1
USE_CURSOR=0

usage() {
  cat <<EOF
Usage: ./tools/jupyter.sh [DEMO] [options]

  DEMO              examples module or package name (default: hub notebook)
  --cursor          open in Cursor (no JupyterLab server)
  -p, --port PORT   JupyterLab port (default: 8888)
  --no-open         prepare notebook / server but do not open UI
  -h, --help        this help

Environment:
  PYDISPLAY_ROOT    pydisplay clone (default: parent of tools/)
  JUPYTER_VENV      Python venv with jupyter deps (default: .venv)

Examples:
  ./tools/jupyter.sh calculator
  ./tools/jupyter.sh calculator --cursor
  ./tools/jupyter.sh pydisplay_demo --cursor

Requires (in JUPYTER_VENV):
  pip install pillow ipywidgets ipyevents jupyterlab
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --cursor)
      USE_CURSOR=1
      shift
      ;;
    -p|--port)
      PORT="${2:?--port requires a number}"
      shift 2
      ;;
    --no-open)
      OPEN=0
      shift
      ;;
    --*)
      echo "jupyter.sh: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [[ -n "$DEMO" ]]; then
        echo "jupyter.sh: unexpected argument: $1" >&2
        usage >&2
        exit 1
      fi
      DEMO="$1"
      shift
      ;;
  esac
done

if [[ ! -d "$SRC/lib" ]]; then
  echo "jupyter.sh: pydisplay src/ not found under $PYDISPLAY_ROOT" >&2
  exit 1
fi

jupyter_bin() {
  if [[ -x "$VENV/bin/jupyter" ]]; then
    echo "$VENV/bin/jupyter"
    return 0
  fi
  if command -v jupyter >/dev/null 2>&1; then
    command -v jupyter
    return 0
  fi
  return 1
}

ensure_jupyter_deps() {
  if [[ -x "$VENV/bin/python" ]]; then
    return 0
  fi
  cat >&2 <<EOF
jupyter.sh: Jupyter venv not found: $VENV

Create it from the pydisplay repo root:

  cd $PYDISPLAY_ROOT
  python3 -m venv .venv
  .venv/bin/pip install pillow ipywidgets ipyevents jupyterlab

Or set JUPYTER_VENV to an existing environment.
EOF
  exit 1
}

resolve_import() {
  local demo="$1"
  local py="$SRC/examples/${demo}.py"
  local pkg="$SRC/examples/${demo}"
  if [[ -f "$py" ]]; then
    echo "import ${demo}"
    return 0
  fi
  if [[ -f "$pkg/__init__.py" ]]; then
    echo "import ${demo}"
    return 0
  fi
  if [[ -f "$pkg/${demo}.py" ]]; then
    echo "import ${demo}.${demo}"
    return 0
  fi
  echo "jupyter.sh: no example src/examples/${demo}.py or package ${demo}/" >&2
  exit 1
}

write_run_notebook() {
  local demo="$1"
  local out="$2"
  local import_line
  import_line="$(resolve_import "$demo")"

  mkdir -p "$(dirname "$out")"
  DEMO="$demo" IMPORT_LINE="$import_line" OUT="$out" "$VENV/bin/python" <<'PY'
import json
import os
from pathlib import Path

demo = os.environ["DEMO"]
import_line = os.environ["IMPORT_LINE"]
out = Path(os.environ["OUT"])

cells = [
    {
        "cell_type": "markdown",
        "id": "intro",
        "metadata": {},
        "source": [
            f"# pydisplay — {demo}\n",
            "\n",
            "Generated by `./tools/jupyter.sh`. Click the **ipywidgets Image** for touch input.\n",
            "\n",
            "**Cursor / VS Code:** select the `.venv` kernel, then run all cells.\n",
            "**Stop:** Kernel → Restart (async examples run in the background).\n",
        ],
    },
    {
        "cell_type": "code",
        "id": "bootstrap",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            "import lib.path\n",
        ],
    },
    {
        "cell_type": "code",
        "id": "run",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": [
            f"{import_line}\n",
        ],
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    },
    "cells": cells,
}

out.write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")
print(out)
PY
}

open_url() {
  local url="$1"
  if [[ "$OPEN" -eq 0 ]]; then
    return 0
  fi
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 &
  elif command -v wslview >/dev/null 2>&1; then
    wslview "$url" >/dev/null 2>&1 &
  elif [[ -n "${WSL_DISTRO_NAME:-}" ]] && command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "" "$url" >/dev/null 2>&1 &
  else
    echo "jupyter.sh: no browser opener found; open manually:"
    echo "  $url"
  fi
}

open_cursor() {
  local path="$1"
  local editor="${CURSOR:-cursor}"
  if [[ "$OPEN" -eq 0 ]]; then
    return 0
  fi
  if ! command -v "$editor" >/dev/null 2>&1; then
    echo "jupyter.sh: $editor not found in PATH (set CURSOR to override)" >&2
    echo "jupyter.sh: notebook: $path" >&2
    exit 1
  fi
  "$editor" "$path" >/dev/null 2>&1 &
}

server_ready() {
  curl -sf -o /dev/null "http://127.0.0.1:${PORT}/api/status" 2>/dev/null
}

server_healthy() {
  server_ready && curl -sf -o /dev/null "http://127.0.0.1:${PORT}/lab" 2>/dev/null
}

stop_server_on_port() {
  local pids=""
  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -ti :"${PORT}" 2>/dev/null || true)"
  elif command -v fuser >/dev/null 2>&1; then
    fuser -k "${PORT}/tcp" 2>/dev/null || true
    sleep 0.5
    return 0
  fi
  if [[ -n "$pids" ]]; then
    echo "jupyter.sh: stopping server on port ${PORT}"
    # shellcheck disable=SC2086
    kill $pids 2>/dev/null || true
    sleep 0.5
  fi
}

wait_for_server() {
  local i
  for i in $(seq 1 80); do
    if server_healthy; then
      return 0
    fi
    sleep 0.15
  done
  return 1
}

NOTEBOOK=""
if [[ -n "$DEMO" ]]; then
  NOTEBOOK="$SRC/run-${DEMO}.ipynb"
  ensure_jupyter_deps
  write_run_notebook "$DEMO" "$NOTEBOOK" >/dev/null
  echo "jupyter.sh: wrote $NOTEBOOK"
else
  NOTEBOOK="$HUB_NOTEBOOK"
  if [[ ! -f "$NOTEBOOK" ]]; then
    echo "jupyter.sh: hub notebook not found: $NOTEBOOK" >&2
    exit 1
  fi
fi

if [[ "$USE_CURSOR" -eq 1 ]]; then
  echo "jupyter.sh: opening in Cursor — select kernel $VENV/bin/python, run all cells"
  open_cursor "$NOTEBOOK"
  echo "jupyter.sh: $NOTEBOOK"
  exit 0
fi

ensure_jupyter_deps
JUPYTER="$(jupyter_bin)"

SERVER_PID=""
cleanup() {
  if [[ -n "$SERVER_PID" ]]; then
    kill "$SERVER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

BASE="http://127.0.0.1:${PORT}"
# Path relative to notebook-dir (src/)
if [[ -n "$DEMO" ]]; then
  LAB_PATH="run-${DEMO}.ipynb"
else
  LAB_PATH="jupyter_notebook.ipynb"
fi
URL="${BASE}/lab/tree/${LAB_PATH}"

if server_healthy; then
  echo "jupyter.sh: reusing JupyterLab at ${BASE}"
else
  if server_ready; then
    echo "jupyter.sh: replacing unhealthy JupyterLab on port ${PORT}" >&2
    stop_server_on_port
  fi
  echo "jupyter.sh: starting JupyterLab on ${BASE} (notebook-dir=${SRC})"
  "$JUPYTER" lab \
    --no-browser \
    --notebook-dir="$SRC" \
    --port="$PORT" \
    --ServerApp.token='' \
    --ServerApp.password='' \
    --ServerApp.disable_check_xsrf=True \
    &
  SERVER_PID=$!
  if ! wait_for_server; then
    echo "jupyter.sh: JupyterLab did not become ready on ${BASE}" >&2
    exit 1
  fi
  if ! server_healthy; then
    echo "jupyter.sh: JupyterLab started but /lab is not healthy — check ${VENV}/bin/jupyter" >&2
    exit 1
  fi
fi

echo "jupyter.sh: ${URL}"
echo "jupyter.sh: kernel: ${VENV}/bin/python"
open_url "$URL"

if [[ -n "$SERVER_PID" ]]; then
  echo "jupyter.sh: Ctrl+C to stop JupyterLab"
  wait "$SERVER_PID"
fi
