#!/usr/bin/env bash
# Start pydisplay's PyScript dev server and open a gallery demo in the browser.
#
# Demo URLs come from web/pyscript/index.html (generated by
# scripts/pyscript_gen_packages.py) — the same load.html?modules=… /
# load.html?manifests=… links as the card grid.
#
# Usage (from repo root):
#   ./tools/pyscript.sh calc_lvgl
#   ./tools/pyscript.sh chango
#   ./tools/pyscript.sh                         # gallery
#   ./tools/pyscript.sh calc_lvgl -p 8080
#   ./tools/pyscript.sh calc_lvgl --no-open
#   ./tools/pyscript.sh calc_lvgl --kill-port
#   ./tools/pyscript.sh --module bouncing_balls
#   ./tools/pyscript.sh --manifest chango

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYDISPLAY_ROOT="${PYDISPLAY_ROOT:-$(cd "$_SCRIPT_DIR/.." && pwd)}"
SERVE="$PYDISPLAY_ROOT/tools/serve.py"
PYSCRIPT_DIR="$PYDISPLAY_ROOT/web/pyscript"
INDEX="$PYSCRIPT_DIR/index.html"
PORT=8000
DEMO=""
MODE="" # manifest | module | "" (auto from gallery)
OPEN=1
DEBUG=0
KILL_PORT=0
AUTOTEST=0
DURATION=5

usage() {
  cat <<EOF
Usage: ./tools/pyscript.sh [DEMO] [options]

  DEMO              gallery demo name (default: open gallery index)
  --manifest NAME   force load.html?manifests=NAME (gallery lookup preferred)
  --module NAME     force load.html?modules=… (gallery lookup preferred)
  -p, --port PORT   port (default: 8000)
  --kill-port       kill any existing listener on PORT, then start serve.py
  --debug           open embed.html with the same query + debug=1
  --autotest        headless Playwright smoke (EXAMPLE_RESULT); implies --no-open.
                    Streams the page #log panel to stdout in real time.
  --auto-test       alias for --autotest
  --duration SEC    autotest duration seconds (default: 5)
  --no-open         start/reuse server and print URL; do not open a browser
  -h, --help        this help

DEMO is resolved against the card hrefs in web/pyscript/index.html, so names
like calc_lvgl open load.html?modules=calc_lvgl,calc_engine (and any
&packages=… the gallery generated).

If something is already listening on PORT, reuse it (do not bind again).
Use --kill-port when you want a fresh serve.py on that port.

Environment:
  PYDISPLAY_ROOT    pydisplay clone (default: parent of tools/)

Examples:
  ./tools/pyscript.sh calc_lvgl
  ./tools/pyscript.sh chango
  ./tools/pyscript.sh nano_gui_simpletest
  ./tools/pyscript.sh calc_lvgl --kill-port
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --manifest)
      MODE=manifest
      DEMO="${2:?--manifest requires a name}"
      shift 2
      ;;
    --module)
      MODE=module
      DEMO="${2:?--module requires a name}"
      shift 2
      ;;
    -p|--port)
      PORT="${2:?--port requires a number}"
      shift 2
      ;;
    --kill-port)
      KILL_PORT=1
      shift
      ;;
    --debug)
      DEBUG=1
      shift
      ;;
    --autotest|--auto-test)
      AUTOTEST=1
      OPEN=0
      shift
      ;;
    --duration)
      DURATION="${2:?--duration requires seconds}"
      shift 2
      ;;
    --no-open)
      OPEN=0
      shift
      ;;
    --*)
      echo "pyscript.sh: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      if [[ -n "$DEMO" ]]; then
        echo "pyscript.sh: unexpected argument: $1" >&2
        usage >&2
        exit 1
      fi
      DEMO="$1"
      shift
      ;;
  esac
done

if [[ ! -f "$SERVE" ]]; then
  echo "pyscript.sh: serve.py not found: $SERVE" >&2
  exit 1
fi

if [[ ! -f "$INDEX" ]]; then
  echo "pyscript.sh: gallery index not found: $INDEX" >&2
  exit 1
fi

# Relative paths from index.html card hrefs, e.g. load.html?modules=calc_lvgl,calc_engine
gallery_hrefs() {
  grep -oE 'href="load\.html\?[^"]+"' "$INDEX" | sed 's/^href="//;s/"$//'
}

# Print matching load.html?… href for DEMO, or empty if none.
# Prefer: exact manifests=, then modules= where DEMO is the first stem.
lookup_gallery_href() {
  local demo="$1"
  local prefer="${2:-}" # module | manifest | ""
  local href query
  local manifest_hit="" module_hit=""

  while IFS= read -r href; do
    [[ -z "$href" ]] && continue
    query="${href#load.html?}"
    case "$query" in
      manifests="${demo}"|manifests="${demo}"\&*)
        manifest_hit="$href"
        ;;
      modules="${demo}"|modules="${demo},"*|modules="${demo}"\&*)
        module_hit="$href"
        ;;
    esac
  done < <(gallery_hrefs)

  if [[ "$prefer" == "manifest" ]]; then
    [[ -n "$manifest_hit" ]] && { printf '%s\n' "$manifest_hit"; return 0; }
    return 1
  fi
  if [[ "$prefer" == "module" ]]; then
    [[ -n "$module_hit" ]] && { printf '%s\n' "$module_hit"; return 0; }
    return 1
  fi
  if [[ -n "$manifest_hit" ]]; then
    printf '%s\n' "$manifest_hit"
    return 0
  fi
  if [[ -n "$module_hit" ]]; then
    printf '%s\n' "$module_hit"
    return 0
  fi
  return 1
}

list_gallery_demos() {
  local href query
  while IFS= read -r href; do
    query="${href#load.html?}"
    case "$query" in
      modules=*)
        query="${query#modules=}"
        query="${query%%&*}"
        printf '  %s\n' "${query%%,*}"
        ;;
      manifests=*)
        query="${query#manifests=}"
        query="${query%%&*}"
        printf '  %s\n' "$query"
        ;;
    esac
  done < <(gallery_hrefs)
}

resolve_rel_path() {
  local demo="$1"
  local href=""

  if [[ -z "$demo" ]]; then
    printf '%s\n' "index.html"
    return 0
  fi

  case "$demo" in
    index|gallery)
      printf '%s\n' "index.html"
      return 0
      ;;
    repl|simple)
      printf '%s\n' "${demo}.html"
      return 0
      ;;
  esac

  if href="$(lookup_gallery_href "$demo" "$MODE")"; then
    printf '%s\n' "$href"
    return 0
  fi

  # Forced --module / --manifest without a gallery card: build a minimal URL.
  if [[ "$MODE" == "manifest" ]]; then
    if [[ -f "$PYSCRIPT_DIR/${demo}.json" ]]; then
      printf '%s\n' "load.html?manifests=${demo}"
      return 0
    fi
    echo "pyscript.sh: no gallery card or manifest for '${demo}'" >&2
    echo "pyscript.sh: gallery demos:" >&2
    list_gallery_demos >&2
    return 1
  fi
  if [[ "$MODE" == "module" ]]; then
    if [[ -f "$PYDISPLAY_ROOT/src/examples/${demo}.py" ]] \
      || [[ -d "$PYDISPLAY_ROOT/src/examples/${demo}" ]]; then
      printf '%s\n' "load.html?modules=${demo}"
      return 0
    fi
    echo "pyscript.sh: no gallery card or module for '${demo}'" >&2
    echo "pyscript.sh: gallery demos:" >&2
    list_gallery_demos >&2
    return 1
  fi

  echo "pyscript.sh: '${demo}' is not a gallery demo in ${INDEX}" >&2
  echo "pyscript.sh: gallery demos:" >&2
  list_gallery_demos >&2
  return 1
}

REL_PATH="$(resolve_rel_path "$DEMO")" || exit 1

BASE="http://127.0.0.1:${PORT}"
PAGE_ROOT="${BASE}/web/pyscript"

if [[ "$DEBUG" -eq 1 ]] || [[ "$AUTOTEST" -eq 1 ]]; then
  case "$REL_PATH" in
    load.html\?*)
      URL="${PAGE_ROOT}/embed.html?${REL_PATH#load.html?}"
      ;;
    *.html)
      URL="${PAGE_ROOT}/${REL_PATH}"
      ;;
    *)
      URL="${PAGE_ROOT}/${REL_PATH}"
      ;;
  esac
  if [[ "$URL" == *"?"* ]]; then
    SEP="&"
  else
    SEP="?"
  fi
  if [[ "$DEBUG" -eq 1 ]]; then
    URL="${URL}${SEP}debug=1"
    SEP="&"
  fi
  if [[ "$AUTOTEST" -eq 1 ]]; then
    URL="${URL}${SEP}autotest=1&duration=${DURATION}"
  fi
else
  URL="${PAGE_ROOT}/${REL_PATH}"
fi

server_ready() {
  curl -sf -o /dev/null "${PAGE_ROOT}/load.html" 2>/dev/null
}

port_listening() {
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"${PORT}" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "( sport = :${PORT} )" 2>/dev/null | grep -q LISTEN
    return $?
  fi
  if command -v fuser >/dev/null 2>&1; then
    fuser "${PORT}/tcp" >/dev/null 2>&1
    return $?
  fi
  (echo >/dev/tcp/127.0.0.1/"${PORT}") >/dev/null 2>&1
}

stop_listener_on_port() {
  local pids=""
  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -tiTCP:"${PORT}" -sTCP:LISTEN 2>/dev/null || true)"
  elif command -v fuser >/dev/null 2>&1; then
    echo "pyscript.sh: killing listener on port ${PORT}"
    fuser -k "${PORT}/tcp" 2>/dev/null || true
    sleep 0.5
    return 0
  elif command -v ss >/dev/null 2>&1; then
    pids="$(ss -ltnp "( sport = :${PORT} )" 2>/dev/null \
      | sed -n 's/.*pid=\([0-9][0-9]*\).*/\1/p' | sort -u || true)"
  fi
  if [[ -n "$pids" ]]; then
    echo "pyscript.sh: killing listener on port ${PORT} (pid ${pids//$'\n'/ })"
    # shellcheck disable=SC2086
    kill $pids 2>/dev/null || true
    sleep 0.5
  fi
}

wait_for_server() {
  local i
  for i in $(seq 1 50); do
    if server_ready; then
      return 0
    fi
    sleep 0.1
  done
  return 1
}

open_url() {
  local url="$1"
  if [[ "$OPEN" -eq 0 ]]; then
    return 0
  fi
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 &
  elif command -v wslview >/dev/null 2>&1; then
    wslview "$url" >/dev/null 2>&1 &
  elif [[ -n "${WSL_DISTRO_NAME:-}" ]] && command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "" "$url" >/dev/null 2>&1 &
  else
    echo "pyscript.sh: no browser opener found; open manually:"
    echo "  $url"
    return 0
  fi
}

SERVER_PID=""
cleanup() {
  if [[ -n "$SERVER_PID" ]]; then
    kill "$SERVER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

if [[ "$KILL_PORT" -eq 1 ]]; then
  stop_listener_on_port
  if port_listening; then
    echo "pyscript.sh: port ${PORT} still in use after --kill-port" >&2
    exit 1
  fi
fi

if [[ "$KILL_PORT" -eq 0 ]] && port_listening; then
  echo "pyscript.sh: reusing listener on ${BASE}"
  if ! server_ready; then
    echo "pyscript.sh: warning: port ${PORT} is in use but ${PAGE_ROOT}/load.html is not ready" >&2
    echo "pyscript.sh: use --kill-port to replace the listener" >&2
  fi
else
  echo "pyscript.sh: starting ${SERVE} on ${BASE}"
  python3 "$SERVE" -p "$PORT" &
  SERVER_PID=$!
  if ! wait_for_server; then
    echo "pyscript.sh: server did not become ready on ${BASE}" >&2
    exit 1
  fi
fi

echo "pyscript.sh: ${URL}"

if [[ "$AUTOTEST" -eq 1 ]]; then
  if [[ -z "$DEMO" ]] || [[ "$DEMO" == "index" ]] || [[ "$DEMO" == "gallery" ]]; then
    echo "pyscript.sh: --autotest requires a demo name" >&2
    exit 1
  fi
  # Prefer repo venv Playwright; fall back to python3 on PATH.
  PY="${PYDISPLAY_ROOT}/.venv/bin/python"
  if [[ ! -x "$PY" ]]; then
    PY="python3"
  fi
  TIMEOUT_MS=$(( (DURATION + 40) * 1000 ))
  export PYSCRIPT_AUTOTEST_URL="$URL"
  export PYSCRIPT_AUTOTEST_DURATION="$DURATION"
  export PYSCRIPT_AUTOTEST_TIMEOUT_S="$(( DURATION + 40 ))"
  set +e
  "$PY" "${PYDISPLAY_ROOT}/tools/pyscript_autotest.py" "$URL" \
    --duration "$DURATION" \
    --timeout "$(( DURATION + 40 ))"
  rc=$?
  set -e
  exit "$rc"
fi

open_url "$URL"

if [[ -n "$SERVER_PID" ]]; then
  echo "pyscript.sh: Ctrl+C to stop the server"
  wait "$SERVER_PID"
fi
