#!/usr/bin/env bash
# Regenerate derived artifacts in the pydisplay repo.
#
# Usage:
#   ./tools/regenerate.sh           # apply updates (default)
#   ./tools/regenerate.sh --audit   # show drift vs src/, then restore
#   ./tools/regenerate.sh --help

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

GENERATED_BY_GEN_REPO_PACKAGES=(
    packages/add_ons.json
    packages/displaysys.json
    packages/eventsys.json
    packages/examples.json
    packages/graphics.json
    packages/multimer.json
    packages/pydisplay-bundle.json
    wokwi/pydisplay-bundle.json
    html/pyscript.toml
)

MANUAL_PACKAGES=(
    packages/i80bus.json
    packages/spibus.json
)

usage() {
    cat <<'EOF'
Usage: ./tools/regenerate.sh [OPTION]

Regenerate files derived from src/ for GitHub installs and PyScript.

Options:
  (none)        Run gen_repo_packages.py and update committed artifacts.
  --audit, -a   Compare generated output to the working tree, print a summary,
                then restore the original files (no changes kept).
  --help, -h    Show this message.

Generated by gen_repo_packages.py:
  packages/{add_ons,displaysys,eventsys,examples,graphics,multimer,
            pydisplay-bundle}.json
  wokwi/pydisplay-bundle.json
  html/pyscript.toml

Not generated here (edit manually when drivers/bus/ changes):
  packages/i80bus.json
  packages/spibus.json

Other tools (see tools/README.md):
  gen_ref_pages.py       — runs automatically via mkdocs build
  gen_library_packages.sh  — micropython-lib / PyPI publishing
  build.py                 — mip index for micropython-lib gh-pages
  convert_md_png_to_pbm.py — Material Design icon conversion
EOF
}

list_package_diff() {
    python3 - "$1" "$2" <<'PY'
import json
import sys

def dest_paths(pkg_data):
    return {entry[0] for entry in pkg_data.get("urls", [])}

old_path, new_path = sys.argv[1], sys.argv[2]
with open(old_path) as f:
    old = json.load(f)
with open(new_path) as f:
    new = json.load(f)
old_set = dest_paths(old)
new_set = dest_paths(new)
added = sorted(new_set - old_set)
removed = sorted(old_set - new_set)
if not added and not removed:
    sys.exit(0)
name = old_path.rsplit("/", 1)[-1]
print(f"\n{name}:")
for path in added:
    print(f"  + {path}")
for path in removed:
    print(f"  - {path}")
PY
}

audit_repo_packages() {
    local tmp
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' RETURN

    echo "Backing up generated files to $tmp"
    cp -a packages "$tmp/"
    cp html/pyscript.toml "$tmp/"

    echo "Running tools/gen_repo_packages.py..."
    python3 tools/gen_repo_packages.py

    echo
    echo "=== File-level diff ==="
    local changed=0
    for path in "${GENERATED_BY_GEN_REPO_PACKAGES[@]}"; do
        case "$path" in
            packages/*)
                if ! diff -q "$tmp/packages/${path#packages/}" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
            html/pyscript.toml)
                if ! diff -q "$tmp/pyscript.toml" "$path" >/dev/null 2>&1; then
                    echo "changed: $path"
                    changed=1
                fi
                ;;
        esac
    done
    if [[ "$changed" -eq 0 ]]; then
        echo "No differences — generated files match src/."
    fi

    echo
    echo "=== Package entry diff (dest paths) ==="
    for path in "${GENERATED_BY_GEN_REPO_PACKAGES[@]}"; do
        case "$path" in
            packages/*)
                list_package_diff \
                    "$tmp/packages/${path#packages/}" \
                    "$path" || true
                ;;
        esac
    done

    echo
    echo "=== pyscript.toml line diff (source files only) ==="
    python3 - "$tmp/pyscript.toml" html/pyscript.toml <<'PY'
import sys

def interesting(line):
    return "__pycache__" not in line and ".pyc" not in line

old = open(sys.argv[1]).read().splitlines()
new = open(sys.argv[2]).read().splitlines()
added = [line for line in sorted(set(new) - set(old)) if interesting(line)]
removed = [line for line in sorted(set(old) - set(new)) if interesting(line)]
if added:
    print("Added:")
    for line in added:
        print(f"  + {line}")
if removed:
    print("Removed:")
    for line in removed:
        print(f"  - {line}")
if not added and not removed:
    print("No meaningful line differences.")
PY

    echo
    echo "=== Manual packages (not checked by generator) ==="
    for path in "${MANUAL_PACKAGES[@]}"; do
        python3 - "$path" <<'PY'
import json
import os
import sys

path = sys.argv[1]
with open(path) as f:
    data = json.load(f)
print(f"\n{path}:")
listed = set()
for dest, url in data["urls"]:
    listed.add(dest)
    disk = os.path.join("drivers/bus", os.path.basename(dest))
    status = "OK" if os.path.isfile(disk) else "MISSING"
    print(f"  {status}  {dest}")
for name in sorted(os.listdir("drivers/bus")):
    if not name.endswith(".py"):
        continue
    if name not in listed:
        print(f"  note  drivers/bus/{name} exists but is not listed")
PY
    done

    echo
    echo "Restoring original files (audit mode does not keep changes)."
    cp -a "$tmp/packages/." packages/
    cp "$tmp/pyscript.toml" html/pyscript.toml
}

regenerate_repo_packages() {
    echo "Running tools/gen_repo_packages.py..."
    python3 tools/gen_repo_packages.py
    echo
    echo "Updated:"
    for path in "${GENERATED_BY_GEN_REPO_PACKAGES[@]}"; do
        echo "  $path"
    done
    echo
    echo "Remember to review git diff. Manual packages were not changed:"
    for path in "${MANUAL_PACKAGES[@]}"; do
        echo "  $path"
    done
}

case "${1:-}" in
    --audit|-a)
        audit_repo_packages
        ;;
    --help|-h)
        usage
        ;;
    "" )
        regenerate_repo_packages
        ;;
    *)
        echo "Unknown option: $1" >&2
        usage >&2
        exit 1
        ;;
esac
