kind = "busdisplay_spi"
slug = "ili9341_eyespi_qtpy_rp2040"
title = "QT Py RP2040 with EyeSPI and ILI9341 2.8\" display"
title_cp = "QT Py RP2040 with EyeSPI and ILI9341 2.8\" display — CircuitPython"
out = "busdisplay/spi"
circuitpython = true
mp_gc_collect = true

[display]
module = "ili9341"
class = "ILI9341"
width = 240
height = 320
colstart = 0
rowstart = 0
rotation = 0
mirrored = false
color_depth = 16
bgr = true
reverse_bytes_in_word = true
invert = false
brightness = 1.0
backlight_pin = "None"
backlight_on_high = true
reset_pin = "None"
reset_high = true
power_pin = "None"
power_on_high = true

[bus.mp.spi]
id = 0
baudrate = 60_000_000
sck = 6
mosi = 3
miso = 4
dc = 5
cs = 20

[touch]
module = "ft6x36"
class = "FT6x36"
read = "get_positions"
rotation_table = [6, 3, 0, 5]

[touch.mp.i2c]
id = 0
sda = 24
scl = 25
freq = 100_000

[package]
display_driver = "ili9341"
touch_driver = "ft6x36"
deps_mp = ["spibus"]
