kind = "busdisplay_spi"
slug = "pico-lcd-1.8"
title = "Waveshare Pico-LCD-1.8 128x160 ST7735S display"
title_cp = "Waveshare Pico-LCD-1.8 128x160 ST7735R — CircuitPython"
out = "busdisplay/spi"
circuitpython = true

[display]
module = "st7735r_1"
class = "ST7735R"
width = 160
height = 128
colstart = 1
rowstart = 2
rotation = 0
mirrored = false
color_depth = 16
bgr = true
reverse_bytes_in_word = true
invert = false
brightness = 1.0
backlight_pin = 13
backlight_on_high = true
reset_pin = 12
reset_high = false
power_pin = "None"
power_on_high = true

[display.cp]
width = 160
height = 128
colstart = 1
rowstart = 2
rotation = 0
mirrored = false
color_depth = 16
bgr = true
reverse_bytes_in_word = true
invert = false
brightness = 1.0
backlight_pin = "board.GP13"
backlight_on_high = true
reset_high = false

[bus.mp.spi]
id = 1
baudrate = 60_000_000
sck = 10
mosi = 11
dc = 8
cs = 9

[bus.cp.fourwire]
command = "board.GP8"
chip_select = "board.GP9"
reset = "board.GP12"
baudrate = 60_000_000

[package]
display_driver = "st7735r_1"
deps_mp = ["spibus"]
