kind = "busdisplay_spi"
slug = "wokwi_ili9341_ft6x36_esp32s3"
title = "Wokwi ESP32S3 and ILI9341 Touchscreen Display"
out = "busdisplay/spi"
circuitpython = false

[display]
module = "ili9341"
class = "ILI9341"
width = 240
height = 320
colstart = 0
rowstart = 0
rotation = 0
mirrored = false
color_depth = 16
bgr = true
reverse_bytes_in_word = true
invert = false
brightness = 1.0
backlight_on_high = true
reset_high = true
power_on_high = true

[bus.mp.spi]
id = 1
baudrate = 60_000_000
sck = 36
mosi = 35
miso = 37
dc = 16
cs = 5

[touch]
module = "ft6x36"
class = "FT6x36"
read = "get_positions"
rotation_table = [6, 3, 0, 5]

[touch.mp.i2c]
id = 0
sda = 7
scl = 6
freq = 100_000

[package]
display_driver = "ili9341"
touch_driver = "ft6x36"
deps_mp = ["spibus"]
