__all__ = ['AutoDisplay', 'host_kind']

def host_kind(): ...
def AutoDisplay(width: int = 320, height: int = 240, rotation: int = 0, scale: float = 1.0, title: str = 'displaydev', canvas_id: str = 'display_canvas', *, quiet: bool = False): ...
