from ._async_timer import AsyncTimer as AsyncTimer
from ._schedule import schedule as schedule
from ._ticks import monotonic as monotonic, run_deadline_hook as run_deadline_hook, set_deadline_hook as set_deadline_hook, ticks_add as ticks_add, ticks_diff as ticks_diff, ticks_less as ticks_less, ticks_ms as ticks_ms
from ._timer import Timer as Timer
from _typeshed import Incomplete

__all__ = ['AsyncTimer', 'Timer', 'asyncio', 'backend_name', 'backends', 'backends_available', 'install_asyncio_compat', 'loop_running', 'monotonic', 'run_deadline_hook', 'schedule', 'set_deadline_hook', 'sleep_ms', 'ticks_add', 'ticks_diff', 'ticks_less', 'ticks_ms', 'use_backend', 'uses_signals']

asyncio: Incomplete
sleep_ms: Incomplete

def loop_running(): ...
def backend_name(): ...
def backends(): ...
def backends_available(): ...
def use_backend(name): ...
def uses_signals(): ...
def install_asyncio_compat(): ...

