from ._ticks import ticks_add as ticks_add, ticks_diff as ticks_diff
from _typeshed import Incomplete
from collections.abc import Generator

class CancelledError(BaseException): ...
class TimeoutError(Exception): ...

class SingletonGenerator:
    state: Incomplete
    exc: Incomplete
    def __init__(self) -> None: ...
    def __iter__(self): ...
    def __next__(self) -> None: ...

class Event:
    state: bool
    waiting: Incomplete
    def __init__(self) -> None: ...
    def is_set(self): ...
    def set(self) -> None: ...
    def clear(self) -> None: ...
    def wait(self) -> Generator[None, None, Incomplete]: ...

def sleep_ms(t, sgen=...): ...
def sleep(t): ...

class IOQueue:
    poller: Incomplete
    map: Incomplete
    def __init__(self) -> None: ...
    def queue_read(self, s) -> None: ...
    def queue_write(self, s) -> None: ...
    def remove(self, task) -> None: ...
    def wait_io_event(self, dt) -> None: ...

def create_task(coro): ...
def ensure_future(aw): ...
def run_until_complete(main_task=None): ...
def run(coro): ...

cur_task: Incomplete

class Loop:
    def create_task(coro): ...
    def run_forever() -> None: ...
    def run_until_complete(aw): ...
    def stop() -> None: ...
    def close() -> None: ...
    def set_exception_handler(handler) -> None: ...
    def get_exception_handler(): ...
    def default_exception_handler(loop, context) -> None: ...
    def call_exception_handler(context) -> None: ...

def get_event_loop(runq_len: int = 0, waitq_len: int = 0): ...
def get_running_loop(): ...
def current_task(): ...
def new_event_loop(): ...
