from _typeshed import Incomplete

def ticks_ms(): ...
def monotonic(): ...

ticks_ms: Incomplete
ticks_add: Incomplete
ticks_diff: Incomplete

def ticks_less(ticks1, ticks2): ...
def set_deadline_hook(hook) -> None: ...
def run_deadline_hook(): ...

sleep_ms: Incomplete
