from _typeshed import Incomplete

def ticks_ms(): ...
def monotonic(): ...
def ticks_add(ticks, delta): ...
def ticks_diff(ticks1, ticks2): ...
def ticks_less(ticks1, ticks2): ...
def set_deadline_hook(hook) -> None: ...
def run_deadline_hook(): ...

sleep_ms: Incomplete
