__all__ = ['BaseEventLoop', 'Server', 'iscoroutinefunction', 'iscoroutine', 'AbstractEventLoopPolicy', 'AbstractEventLoop', 'AbstractServer', 'Handle', 'TimerHandle', 'get_event_loop_policy', 'set_event_loop_policy', 'get_event_loop', 'set_event_loop', 'new_event_loop', 'get_child_watcher', 'set_child_watcher', '_set_running_loop', 'get_running_loop', '_get_running_loop', 'BrokenBarrierError', 'CancelledError', 'InvalidStateError', 'TimeoutError', 'IncompleteReadError', 'LimitOverrunError', 'SendfileNotAvailableError', 'Future', 'wrap_future', 'isfuture', 'Lock', 'Event', 'Condition', 'Semaphore', 'BoundedSemaphore', 'Barrier', 'BaseProtocol', 'Protocol', 'DatagramProtocol', 'SubprocessProtocol', 'BufferedProtocol', 'Runner', 'run', 'Queue', 'PriorityQueue', 'LifoQueue', 'QueueFull', 'QueueEmpty', 'StreamReader', 'StreamWriter', 'StreamReaderProtocol', 'open_connection', 'start_server', 'open_unix_connection', 'start_unix_server', 'create_subprocess_exec', 'create_subprocess_shell', 'Task', 'create_task', 'FIRST_COMPLETED', 'FIRST_EXCEPTION', 'ALL_COMPLETED', 'wait', 'wait_for', 'as_completed', 'sleep', 'gather', 'shield', 'ensure_future', 'run_coroutine_threadsafe', 'current_task', 'all_tasks', 'create_eager_task_factory', 'eager_task_factory', '_register_task', '_unregister_task', '_enter_task', '_leave_task', 'TaskGroup', 'to_thread', 'Timeout', 'timeout', 'timeout_at', 'BaseTransport', 'ReadTransport', 'WriteTransport', 'Transport', 'DatagramTransport', 'SubprocessTransport', 'SelectorEventLoop', 'AbstractChildWatcher', 'SafeChildWatcher', 'FastChildWatcher', 'PidfdChildWatcher', 'MultiLoopChildWatcher', 'ThreadedChildWatcher', 'DefaultEventLoopPolicy']

def run(coro): ...
def new_event_loop(): ...
def sleep(delay): ...

# Names in __all__ with no definition:
#   ALL_COMPLETED
#   AbstractChildWatcher
#   AbstractEventLoop
#   AbstractEventLoopPolicy
#   AbstractServer
#   Barrier
#   BaseEventLoop
#   BaseProtocol
#   BaseTransport
#   BoundedSemaphore
#   BrokenBarrierError
#   BufferedProtocol
#   CancelledError
#   Condition
#   DatagramProtocol
#   DatagramTransport
#   DefaultEventLoopPolicy
#   Event
#   FIRST_COMPLETED
#   FIRST_EXCEPTION
#   FastChildWatcher
#   Future
#   Handle
#   IncompleteReadError
#   InvalidStateError
#   LifoQueue
#   LimitOverrunError
#   Lock
#   MultiLoopChildWatcher
#   PidfdChildWatcher
#   PriorityQueue
#   Protocol
#   Queue
#   QueueEmpty
#   QueueFull
#   ReadTransport
#   Runner
#   SafeChildWatcher
#   SelectorEventLoop
#   Semaphore
#   SendfileNotAvailableError
#   Server
#   StreamReader
#   StreamReaderProtocol
#   StreamWriter
#   SubprocessProtocol
#   SubprocessTransport
#   Task
#   TaskGroup
#   ThreadedChildWatcher
#   Timeout
#   TimeoutError
#   TimerHandle
#   Transport
#   WriteTransport
#   _enter_task
#   _get_running_loop
#   _leave_task
#   _register_task
#   _set_running_loop
#   _unregister_task
#   all_tasks
#   as_completed
#   create_eager_task_factory
#   create_subprocess_exec
#   create_subprocess_shell
#   create_task
#   current_task
#   eager_task_factory
#   ensure_future
#   gather
#   get_child_watcher
#   get_event_loop
#   get_event_loop_policy
#   get_running_loop
#   iscoroutine
#   iscoroutinefunction
#   isfuture
#   open_connection
#   open_unix_connection
#   run_coroutine_threadsafe
#   set_child_watcher
#   set_event_loop
#   set_event_loop_policy
#   shield
#   start_server
#   start_unix_server
#   timeout
#   timeout_at
#   to_thread
#   wait
#   wait_for
#   wrap_future
