import ctypes
from ._core import _TimerCore

__all__ = ['Timer', 'is_async', 'name', 'pump', 'sleep_ms', 'uses_interrupts']

name: str
uses_interrupts: bool
is_async: bool

def pump() -> None: ...
def sleep_ms(ms) -> None: ...
librt = libc

class _timespec(ctypes.Structure): ...
class _itimerspec(ctypes.Structure): ...
class _sigval(ctypes.Union): ...
class _sigevent(ctypes.Structure): ...
librt = libc

class Timer(_TimerCore): ...
